//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Anses.ArgentaC.Negocio.Activos_ServiciosComplementariosWs {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Activos_ServiciosComplementariosWsSoap", Namespace="http://tempuri.org/")]
    public partial class Activos_ServiciosComplementariosWs : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultaAltaTempranaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaCondenadoProcesadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Activos_ServiciosComplementariosWs() {
            this.Url = global::Anses.ArgentaC.Negocio.Properties.Settings.Default.Anses_ArgentaC_Negocio_Activos_ServiciosComplementariosWs_Activos_ServiciosComplementariosWs;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultaAltaTempranaCompletedEventHandler ConsultaAltaTempranaCompleted;
        
        /// <remarks/>
        public event ConsultaCondenadoProcesadoCompletedEventHandler ConsultaCondenadoProcesadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaAltaTemprana", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DatosDeConsultaAltaTemprana[] ConsultaAltaTemprana(decimal cuil) {
            object[] results = this.Invoke("ConsultaAltaTemprana", new object[] {
                        cuil});
            return ((DatosDeConsultaAltaTemprana[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaAltaTempranaAsync(decimal cuil) {
            this.ConsultaAltaTempranaAsync(cuil, null);
        }
        
        /// <remarks/>
        public void ConsultaAltaTempranaAsync(decimal cuil, object userState) {
            if ((this.ConsultaAltaTempranaOperationCompleted == null)) {
                this.ConsultaAltaTempranaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaAltaTempranaOperationCompleted);
            }
            this.InvokeAsync("ConsultaAltaTemprana", new object[] {
                        cuil}, this.ConsultaAltaTempranaOperationCompleted, userState);
        }
        
        private void OnConsultaAltaTempranaOperationCompleted(object arg) {
            if ((this.ConsultaAltaTempranaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaAltaTempranaCompleted(this, new ConsultaAltaTempranaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaCondenadoProcesado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DatosDeConsultaCondenadoProcesado[] ConsultaCondenadoProcesado(decimal cuil) {
            object[] results = this.Invoke("ConsultaCondenadoProcesado", new object[] {
                        cuil});
            return ((DatosDeConsultaCondenadoProcesado[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaCondenadoProcesadoAsync(decimal cuil) {
            this.ConsultaCondenadoProcesadoAsync(cuil, null);
        }
        
        /// <remarks/>
        public void ConsultaCondenadoProcesadoAsync(decimal cuil, object userState) {
            if ((this.ConsultaCondenadoProcesadoOperationCompleted == null)) {
                this.ConsultaCondenadoProcesadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaCondenadoProcesadoOperationCompleted);
            }
            this.InvokeAsync("ConsultaCondenadoProcesado", new object[] {
                        cuil}, this.ConsultaCondenadoProcesadoOperationCompleted, userState);
        }
        
        private void OnConsultaCondenadoProcesadoOperationCompleted(object arg) {
            if ((this.ConsultaCondenadoProcesadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaCondenadoProcesadoCompleted(this, new ConsultaCondenadoProcesadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DatosDeConsultaAltaTemprana {
        
        private decimal cuitField;
        
        private decimal cuilField;
        
        private System.DateTime fechaAltaTempranaField;
        
        private string descripcionAbreviadaMovimientoField;
        
        private System.Nullable<System.DateTime> fechaFinRelacionLaboralField;
        
        /// <remarks/>
        public decimal Cuit {
            get {
                return this.cuitField;
            }
            set {
                this.cuitField = value;
            }
        }
        
        /// <remarks/>
        public decimal Cuil {
            get {
                return this.cuilField;
            }
            set {
                this.cuilField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaAltaTemprana {
            get {
                return this.fechaAltaTempranaField;
            }
            set {
                this.fechaAltaTempranaField = value;
            }
        }
        
        /// <remarks/>
        public string DescripcionAbreviadaMovimiento {
            get {
                return this.descripcionAbreviadaMovimientoField;
            }
            set {
                this.descripcionAbreviadaMovimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaFinRelacionLaboral {
            get {
                return this.fechaFinRelacionLaboralField;
            }
            set {
                this.fechaFinRelacionLaboralField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DatosDeConsultaCondenadoProcesado {
        
        private decimal cuilField;
        
        private System.DateTime fechaCargaField;
        
        private short codigoEstadoField;
        
        private decimal periodoLiquidacionField;
        
        private string tipoInternoField;
        
        private System.Nullable<decimal> cuitField;
        
        /// <remarks/>
        public decimal Cuil {
            get {
                return this.cuilField;
            }
            set {
                this.cuilField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaCarga {
            get {
                return this.fechaCargaField;
            }
            set {
                this.fechaCargaField = value;
            }
        }
        
        /// <remarks/>
        public short CodigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
            }
        }
        
        /// <remarks/>
        public decimal PeriodoLiquidacion {
            get {
                return this.periodoLiquidacionField;
            }
            set {
                this.periodoLiquidacionField = value;
            }
        }
        
        /// <remarks/>
        public string TipoInterno {
            get {
                return this.tipoInternoField;
            }
            set {
                this.tipoInternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Cuit {
            get {
                return this.cuitField;
            }
            set {
                this.cuitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ConsultaAltaTempranaCompletedEventHandler(object sender, ConsultaAltaTempranaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaAltaTempranaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaAltaTempranaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DatosDeConsultaAltaTemprana[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DatosDeConsultaAltaTemprana[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ConsultaCondenadoProcesadoCompletedEventHandler(object sender, ConsultaCondenadoProcesadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaCondenadoProcesadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaCondenadoProcesadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DatosDeConsultaCondenadoProcesado[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DatosDeConsultaCondenadoProcesado[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591