//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Anses.ArgentaC.Negocio.BocaDePagoWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BocaDePagoWSSoap", Namespace="http://BocaDePago.Anses.Gov.Ar/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Resultado))]
    public partial class BocaDePagoWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerBeneficiosDelCUIPOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerExCajasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerProvinciasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarExistenciaNovedadPendienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarHistoricoNovedadOperationCompleted;
        
        private System.Threading.SendOrPostCallback GrabarNovedadOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajarNovedadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarNovedadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaBancoAgenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaDetallesBancoAgenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerDetallesBancoAgenciaPorBcoAgeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerZonasAustralesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerDependenciasHabilitadasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarDependenciaHabilitadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarDependenciaHabilitadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarDependenciaHabilitadaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregarZonaAustralOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarZonaAustralOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarZonaAustralOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BocaDePagoWS() {
            this.Url = global::Anses.ArgentaC.Negocio.Properties.Settings.Default.Anses_ArgentaC_Negocio_BocaDePagoWS_BocaDePagoWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenerBeneficiosDelCUIPCompletedEventHandler ObtenerBeneficiosDelCUIPCompleted;
        
        /// <remarks/>
        public event ObtenerExCajasCompletedEventHandler ObtenerExCajasCompleted;
        
        /// <remarks/>
        public event ObtenerProvinciasCompletedEventHandler ObtenerProvinciasCompleted;
        
        /// <remarks/>
        public event ConsultarExistenciaNovedadPendienteCompletedEventHandler ConsultarExistenciaNovedadPendienteCompleted;
        
        /// <remarks/>
        public event ConsultarHistoricoNovedadCompletedEventHandler ConsultarHistoricoNovedadCompleted;
        
        /// <remarks/>
        public event GrabarNovedadCompletedEventHandler GrabarNovedadCompleted;
        
        /// <remarks/>
        public event BajarNovedadCompletedEventHandler BajarNovedadCompleted;
        
        /// <remarks/>
        public event ModificarNovedadCompletedEventHandler ModificarNovedadCompleted;
        
        /// <remarks/>
        public event ConsultaBancoAgenciaCompletedEventHandler ConsultaBancoAgenciaCompleted;
        
        /// <remarks/>
        public event ConsultaDetallesBancoAgenciaCompletedEventHandler ConsultaDetallesBancoAgenciaCompleted;
        
        /// <remarks/>
        public event ObtenerDetallesBancoAgenciaPorBcoAgeCompletedEventHandler ObtenerDetallesBancoAgenciaPorBcoAgeCompleted;
        
        /// <remarks/>
        public event ObtenerZonasAustralesCompletedEventHandler ObtenerZonasAustralesCompleted;
        
        /// <remarks/>
        public event ObtenerDependenciasHabilitadasCompletedEventHandler ObtenerDependenciasHabilitadasCompleted;
        
        /// <remarks/>
        public event ActualizarDependenciaHabilitadaCompletedEventHandler ActualizarDependenciaHabilitadaCompleted;
        
        /// <remarks/>
        public event AgregarDependenciaHabilitadaCompletedEventHandler AgregarDependenciaHabilitadaCompleted;
        
        /// <remarks/>
        public event EliminarDependenciaHabilitadaCompletedEventHandler EliminarDependenciaHabilitadaCompleted;
        
        /// <remarks/>
        public event AgregarZonaAustralCompletedEventHandler AgregarZonaAustralCompleted;
        
        /// <remarks/>
        public event EliminarZonaAustralCompletedEventHandler EliminarZonaAustralCompleted;
        
        /// <remarks/>
        public event ActualizarZonaAustralCompletedEventHandler ActualizarZonaAustralCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/ObtenerBeneficiosDelCUIP", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BeneficioDetalle[] ObtenerBeneficiosDelCUIP(decimal cuip) {
            object[] results = this.Invoke("ObtenerBeneficiosDelCUIP", new object[] {
                        cuip});
            return ((BeneficioDetalle[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerBeneficiosDelCUIPAsync(decimal cuip) {
            this.ObtenerBeneficiosDelCUIPAsync(cuip, null);
        }
        
        /// <remarks/>
        public void ObtenerBeneficiosDelCUIPAsync(decimal cuip, object userState) {
            if ((this.ObtenerBeneficiosDelCUIPOperationCompleted == null)) {
                this.ObtenerBeneficiosDelCUIPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerBeneficiosDelCUIPOperationCompleted);
            }
            this.InvokeAsync("ObtenerBeneficiosDelCUIP", new object[] {
                        cuip}, this.ObtenerBeneficiosDelCUIPOperationCompleted, userState);
        }
        
        private void OnObtenerBeneficiosDelCUIPOperationCompleted(object arg) {
            if ((this.ObtenerBeneficiosDelCUIPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerBeneficiosDelCUIPCompleted(this, new ObtenerBeneficiosDelCUIPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/ObtenerExCajas", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExCaja[] ObtenerExCajas() {
            object[] results = this.Invoke("ObtenerExCajas", new object[0]);
            return ((ExCaja[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerExCajasAsync() {
            this.ObtenerExCajasAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerExCajasAsync(object userState) {
            if ((this.ObtenerExCajasOperationCompleted == null)) {
                this.ObtenerExCajasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerExCajasOperationCompleted);
            }
            this.InvokeAsync("ObtenerExCajas", new object[0], this.ObtenerExCajasOperationCompleted, userState);
        }
        
        private void OnObtenerExCajasOperationCompleted(object arg) {
            if ((this.ObtenerExCajasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerExCajasCompleted(this, new ObtenerExCajasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/ObtenerProvincias", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Provincia[] ObtenerProvincias() {
            object[] results = this.Invoke("ObtenerProvincias", new object[0]);
            return ((Provincia[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerProvinciasAsync() {
            this.ObtenerProvinciasAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerProvinciasAsync(object userState) {
            if ((this.ObtenerProvinciasOperationCompleted == null)) {
                this.ObtenerProvinciasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerProvinciasOperationCompleted);
            }
            this.InvokeAsync("ObtenerProvincias", new object[0], this.ObtenerProvinciasOperationCompleted, userState);
        }
        
        private void OnObtenerProvinciasOperationCompleted(object arg) {
            if ((this.ObtenerProvinciasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerProvinciasCompleted(this, new ObtenerProvinciasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/ConsultarExistenciaNovedadPendiente", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Novedad[] ConsultarExistenciaNovedadPendiente(long beneficio) {
            object[] results = this.Invoke("ConsultarExistenciaNovedadPendiente", new object[] {
                        beneficio});
            return ((Novedad[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarExistenciaNovedadPendienteAsync(long beneficio) {
            this.ConsultarExistenciaNovedadPendienteAsync(beneficio, null);
        }
        
        /// <remarks/>
        public void ConsultarExistenciaNovedadPendienteAsync(long beneficio, object userState) {
            if ((this.ConsultarExistenciaNovedadPendienteOperationCompleted == null)) {
                this.ConsultarExistenciaNovedadPendienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarExistenciaNovedadPendienteOperationCompleted);
            }
            this.InvokeAsync("ConsultarExistenciaNovedadPendiente", new object[] {
                        beneficio}, this.ConsultarExistenciaNovedadPendienteOperationCompleted, userState);
        }
        
        private void OnConsultarExistenciaNovedadPendienteOperationCompleted(object arg) {
            if ((this.ConsultarExistenciaNovedadPendienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarExistenciaNovedadPendienteCompleted(this, new ConsultarExistenciaNovedadPendienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/ConsultarHistoricoNovedad", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DetalleSolicitud[] ConsultarHistoricoNovedad(long beneficio) {
            object[] results = this.Invoke("ConsultarHistoricoNovedad", new object[] {
                        beneficio});
            return ((DetalleSolicitud[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarHistoricoNovedadAsync(long beneficio) {
            this.ConsultarHistoricoNovedadAsync(beneficio, null);
        }
        
        /// <remarks/>
        public void ConsultarHistoricoNovedadAsync(long beneficio, object userState) {
            if ((this.ConsultarHistoricoNovedadOperationCompleted == null)) {
                this.ConsultarHistoricoNovedadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarHistoricoNovedadOperationCompleted);
            }
            this.InvokeAsync("ConsultarHistoricoNovedad", new object[] {
                        beneficio}, this.ConsultarHistoricoNovedadOperationCompleted, userState);
        }
        
        private void OnConsultarHistoricoNovedadOperationCompleted(object arg) {
            if ((this.ConsultarHistoricoNovedadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarHistoricoNovedadCompleted(this, new ConsultarHistoricoNovedadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/GrabarNovedad", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Confirmacion GrabarNovedad(long beneficio, long cuip, long agentepagador, long oficina, string terminal, string operador, System.DateTime periodo) {
            object[] results = this.Invoke("GrabarNovedad", new object[] {
                        beneficio,
                        cuip,
                        agentepagador,
                        oficina,
                        terminal,
                        operador,
                        periodo});
            return ((Confirmacion)(results[0]));
        }
        
        /// <remarks/>
        public void GrabarNovedadAsync(long beneficio, long cuip, long agentepagador, long oficina, string terminal, string operador, System.DateTime periodo) {
            this.GrabarNovedadAsync(beneficio, cuip, agentepagador, oficina, terminal, operador, periodo, null);
        }
        
        /// <remarks/>
        public void GrabarNovedadAsync(long beneficio, long cuip, long agentepagador, long oficina, string terminal, string operador, System.DateTime periodo, object userState) {
            if ((this.GrabarNovedadOperationCompleted == null)) {
                this.GrabarNovedadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGrabarNovedadOperationCompleted);
            }
            this.InvokeAsync("GrabarNovedad", new object[] {
                        beneficio,
                        cuip,
                        agentepagador,
                        oficina,
                        terminal,
                        operador,
                        periodo}, this.GrabarNovedadOperationCompleted, userState);
        }
        
        private void OnGrabarNovedadOperationCompleted(object arg) {
            if ((this.GrabarNovedadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GrabarNovedadCompleted(this, new GrabarNovedadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/BajarNovedad", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Confirmacion BajarNovedad(long beneficio, long cuip, long oficina, string terminal, string operador) {
            object[] results = this.Invoke("BajarNovedad", new object[] {
                        beneficio,
                        cuip,
                        oficina,
                        terminal,
                        operador});
            return ((Confirmacion)(results[0]));
        }
        
        /// <remarks/>
        public void BajarNovedadAsync(long beneficio, long cuip, long oficina, string terminal, string operador) {
            this.BajarNovedadAsync(beneficio, cuip, oficina, terminal, operador, null);
        }
        
        /// <remarks/>
        public void BajarNovedadAsync(long beneficio, long cuip, long oficina, string terminal, string operador, object userState) {
            if ((this.BajarNovedadOperationCompleted == null)) {
                this.BajarNovedadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajarNovedadOperationCompleted);
            }
            this.InvokeAsync("BajarNovedad", new object[] {
                        beneficio,
                        cuip,
                        oficina,
                        terminal,
                        operador}, this.BajarNovedadOperationCompleted, userState);
        }
        
        private void OnBajarNovedadOperationCompleted(object arg) {
            if ((this.BajarNovedadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajarNovedadCompleted(this, new BajarNovedadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/ModificarNovedad", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Confirmacion ModificarNovedad(long beneficio, long cuip, long agentepagador, long oficina, string terminal, string operador, System.DateTime periodo) {
            object[] results = this.Invoke("ModificarNovedad", new object[] {
                        beneficio,
                        cuip,
                        agentepagador,
                        oficina,
                        terminal,
                        operador,
                        periodo});
            return ((Confirmacion)(results[0]));
        }
        
        /// <remarks/>
        public void ModificarNovedadAsync(long beneficio, long cuip, long agentepagador, long oficina, string terminal, string operador, System.DateTime periodo) {
            this.ModificarNovedadAsync(beneficio, cuip, agentepagador, oficina, terminal, operador, periodo, null);
        }
        
        /// <remarks/>
        public void ModificarNovedadAsync(long beneficio, long cuip, long agentepagador, long oficina, string terminal, string operador, System.DateTime periodo, object userState) {
            if ((this.ModificarNovedadOperationCompleted == null)) {
                this.ModificarNovedadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarNovedadOperationCompleted);
            }
            this.InvokeAsync("ModificarNovedad", new object[] {
                        beneficio,
                        cuip,
                        agentepagador,
                        oficina,
                        terminal,
                        operador,
                        periodo}, this.ModificarNovedadOperationCompleted, userState);
        }
        
        private void OnModificarNovedadOperationCompleted(object arg) {
            if ((this.ModificarNovedadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarNovedadCompleted(this, new ModificarNovedadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/ConsultaBancoAgencia", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BancoAgencia[] ConsultaBancoAgencia(short codigoPostal, short codigoProvincia) {
            object[] results = this.Invoke("ConsultaBancoAgencia", new object[] {
                        codigoPostal,
                        codigoProvincia});
            return ((BancoAgencia[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaBancoAgenciaAsync(short codigoPostal, short codigoProvincia) {
            this.ConsultaBancoAgenciaAsync(codigoPostal, codigoProvincia, null);
        }
        
        /// <remarks/>
        public void ConsultaBancoAgenciaAsync(short codigoPostal, short codigoProvincia, object userState) {
            if ((this.ConsultaBancoAgenciaOperationCompleted == null)) {
                this.ConsultaBancoAgenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaBancoAgenciaOperationCompleted);
            }
            this.InvokeAsync("ConsultaBancoAgencia", new object[] {
                        codigoPostal,
                        codigoProvincia}, this.ConsultaBancoAgenciaOperationCompleted, userState);
        }
        
        private void OnConsultaBancoAgenciaOperationCompleted(object arg) {
            if ((this.ConsultaBancoAgenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaBancoAgenciaCompleted(this, new ConsultaBancoAgenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/ConsultaDetallesBancoAgencia", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BancoAgencia[] ConsultaDetallesBancoAgencia(short cod_banco, short cod_agencia) {
            object[] results = this.Invoke("ConsultaDetallesBancoAgencia", new object[] {
                        cod_banco,
                        cod_agencia});
            return ((BancoAgencia[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaDetallesBancoAgenciaAsync(short cod_banco, short cod_agencia) {
            this.ConsultaDetallesBancoAgenciaAsync(cod_banco, cod_agencia, null);
        }
        
        /// <remarks/>
        public void ConsultaDetallesBancoAgenciaAsync(short cod_banco, short cod_agencia, object userState) {
            if ((this.ConsultaDetallesBancoAgenciaOperationCompleted == null)) {
                this.ConsultaDetallesBancoAgenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaDetallesBancoAgenciaOperationCompleted);
            }
            this.InvokeAsync("ConsultaDetallesBancoAgencia", new object[] {
                        cod_banco,
                        cod_agencia}, this.ConsultaDetallesBancoAgenciaOperationCompleted, userState);
        }
        
        private void OnConsultaDetallesBancoAgenciaOperationCompleted(object arg) {
            if ((this.ConsultaDetallesBancoAgenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaDetallesBancoAgenciaCompleted(this, new ConsultaDetallesBancoAgenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/ObtenerDetallesBancoAgenciaPorBcoAge", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BancoAgencia[] ObtenerDetallesBancoAgenciaPorBcoAge(short cod_banco, short cod_age) {
            object[] results = this.Invoke("ObtenerDetallesBancoAgenciaPorBcoAge", new object[] {
                        cod_banco,
                        cod_age});
            return ((BancoAgencia[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerDetallesBancoAgenciaPorBcoAgeAsync(short cod_banco, short cod_age) {
            this.ObtenerDetallesBancoAgenciaPorBcoAgeAsync(cod_banco, cod_age, null);
        }
        
        /// <remarks/>
        public void ObtenerDetallesBancoAgenciaPorBcoAgeAsync(short cod_banco, short cod_age, object userState) {
            if ((this.ObtenerDetallesBancoAgenciaPorBcoAgeOperationCompleted == null)) {
                this.ObtenerDetallesBancoAgenciaPorBcoAgeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerDetallesBancoAgenciaPorBcoAgeOperationCompleted);
            }
            this.InvokeAsync("ObtenerDetallesBancoAgenciaPorBcoAge", new object[] {
                        cod_banco,
                        cod_age}, this.ObtenerDetallesBancoAgenciaPorBcoAgeOperationCompleted, userState);
        }
        
        private void OnObtenerDetallesBancoAgenciaPorBcoAgeOperationCompleted(object arg) {
            if ((this.ObtenerDetallesBancoAgenciaPorBcoAgeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerDetallesBancoAgenciaPorBcoAgeCompleted(this, new ObtenerDetallesBancoAgenciaPorBcoAgeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/ObtenerZonasAustrales", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ZonaAustral[] ObtenerZonasAustrales() {
            object[] results = this.Invoke("ObtenerZonasAustrales", new object[0]);
            return ((ZonaAustral[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerZonasAustralesAsync() {
            this.ObtenerZonasAustralesAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerZonasAustralesAsync(object userState) {
            if ((this.ObtenerZonasAustralesOperationCompleted == null)) {
                this.ObtenerZonasAustralesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerZonasAustralesOperationCompleted);
            }
            this.InvokeAsync("ObtenerZonasAustrales", new object[0], this.ObtenerZonasAustralesOperationCompleted, userState);
        }
        
        private void OnObtenerZonasAustralesOperationCompleted(object arg) {
            if ((this.ObtenerZonasAustralesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerZonasAustralesCompleted(this, new ObtenerZonasAustralesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/ObtenerDependenciasHabilitadas", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Dependencia[] ObtenerDependenciasHabilitadas() {
            object[] results = this.Invoke("ObtenerDependenciasHabilitadas", new object[0]);
            return ((Dependencia[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerDependenciasHabilitadasAsync() {
            this.ObtenerDependenciasHabilitadasAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerDependenciasHabilitadasAsync(object userState) {
            if ((this.ObtenerDependenciasHabilitadasOperationCompleted == null)) {
                this.ObtenerDependenciasHabilitadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerDependenciasHabilitadasOperationCompleted);
            }
            this.InvokeAsync("ObtenerDependenciasHabilitadas", new object[0], this.ObtenerDependenciasHabilitadasOperationCompleted, userState);
        }
        
        private void OnObtenerDependenciasHabilitadasOperationCompleted(object arg) {
            if ((this.ObtenerDependenciasHabilitadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerDependenciasHabilitadasCompleted(this, new ObtenerDependenciasHabilitadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/ActualizarDependenciaHabilitada", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ActualizarDependenciaHabilitada(long codigo, string descripcion) {
            object[] results = this.Invoke("ActualizarDependenciaHabilitada", new object[] {
                        codigo,
                        descripcion});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarDependenciaHabilitadaAsync(long codigo, string descripcion) {
            this.ActualizarDependenciaHabilitadaAsync(codigo, descripcion, null);
        }
        
        /// <remarks/>
        public void ActualizarDependenciaHabilitadaAsync(long codigo, string descripcion, object userState) {
            if ((this.ActualizarDependenciaHabilitadaOperationCompleted == null)) {
                this.ActualizarDependenciaHabilitadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarDependenciaHabilitadaOperationCompleted);
            }
            this.InvokeAsync("ActualizarDependenciaHabilitada", new object[] {
                        codigo,
                        descripcion}, this.ActualizarDependenciaHabilitadaOperationCompleted, userState);
        }
        
        private void OnActualizarDependenciaHabilitadaOperationCompleted(object arg) {
            if ((this.ActualizarDependenciaHabilitadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarDependenciaHabilitadaCompleted(this, new ActualizarDependenciaHabilitadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/AgregarDependenciaHabilitada", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AgregarDependenciaHabilitada(long codigo, string descripcion) {
            object[] results = this.Invoke("AgregarDependenciaHabilitada", new object[] {
                        codigo,
                        descripcion});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarDependenciaHabilitadaAsync(long codigo, string descripcion) {
            this.AgregarDependenciaHabilitadaAsync(codigo, descripcion, null);
        }
        
        /// <remarks/>
        public void AgregarDependenciaHabilitadaAsync(long codigo, string descripcion, object userState) {
            if ((this.AgregarDependenciaHabilitadaOperationCompleted == null)) {
                this.AgregarDependenciaHabilitadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarDependenciaHabilitadaOperationCompleted);
            }
            this.InvokeAsync("AgregarDependenciaHabilitada", new object[] {
                        codigo,
                        descripcion}, this.AgregarDependenciaHabilitadaOperationCompleted, userState);
        }
        
        private void OnAgregarDependenciaHabilitadaOperationCompleted(object arg) {
            if ((this.AgregarDependenciaHabilitadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarDependenciaHabilitadaCompleted(this, new AgregarDependenciaHabilitadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/EliminarDependenciaHabilitada", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarDependenciaHabilitada(long codigo) {
            object[] results = this.Invoke("EliminarDependenciaHabilitada", new object[] {
                        codigo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarDependenciaHabilitadaAsync(long codigo) {
            this.EliminarDependenciaHabilitadaAsync(codigo, null);
        }
        
        /// <remarks/>
        public void EliminarDependenciaHabilitadaAsync(long codigo, object userState) {
            if ((this.EliminarDependenciaHabilitadaOperationCompleted == null)) {
                this.EliminarDependenciaHabilitadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarDependenciaHabilitadaOperationCompleted);
            }
            this.InvokeAsync("EliminarDependenciaHabilitada", new object[] {
                        codigo}, this.EliminarDependenciaHabilitadaOperationCompleted, userState);
        }
        
        private void OnEliminarDependenciaHabilitadaOperationCompleted(object arg) {
            if ((this.EliminarDependenciaHabilitadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarDependenciaHabilitadaCompleted(this, new EliminarDependenciaHabilitadaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/AgregarZonaAustral", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> AgregarZonaAustral(short id_provincia, string cobertura, short codigopostal, string localidad) {
            object[] results = this.Invoke("AgregarZonaAustral", new object[] {
                        id_provincia,
                        cobertura,
                        codigopostal,
                        localidad});
            return ((System.Nullable<short>)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarZonaAustralAsync(short id_provincia, string cobertura, short codigopostal, string localidad) {
            this.AgregarZonaAustralAsync(id_provincia, cobertura, codigopostal, localidad, null);
        }
        
        /// <remarks/>
        public void AgregarZonaAustralAsync(short id_provincia, string cobertura, short codigopostal, string localidad, object userState) {
            if ((this.AgregarZonaAustralOperationCompleted == null)) {
                this.AgregarZonaAustralOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarZonaAustralOperationCompleted);
            }
            this.InvokeAsync("AgregarZonaAustral", new object[] {
                        id_provincia,
                        cobertura,
                        codigopostal,
                        localidad}, this.AgregarZonaAustralOperationCompleted, userState);
        }
        
        private void OnAgregarZonaAustralOperationCompleted(object arg) {
            if ((this.AgregarZonaAustralCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarZonaAustralCompleted(this, new AgregarZonaAustralCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/EliminarZonaAustral", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EliminarZonaAustral(short codigoprovincia, short codigopostal) {
            object[] results = this.Invoke("EliminarZonaAustral", new object[] {
                        codigoprovincia,
                        codigopostal});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarZonaAustralAsync(short codigoprovincia, short codigopostal) {
            this.EliminarZonaAustralAsync(codigoprovincia, codigopostal, null);
        }
        
        /// <remarks/>
        public void EliminarZonaAustralAsync(short codigoprovincia, short codigopostal, object userState) {
            if ((this.EliminarZonaAustralOperationCompleted == null)) {
                this.EliminarZonaAustralOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarZonaAustralOperationCompleted);
            }
            this.InvokeAsync("EliminarZonaAustral", new object[] {
                        codigoprovincia,
                        codigopostal}, this.EliminarZonaAustralOperationCompleted, userState);
        }
        
        private void OnEliminarZonaAustralOperationCompleted(object arg) {
            if ((this.EliminarZonaAustralCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarZonaAustralCompleted(this, new EliminarZonaAustralCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://BocaDePago.Anses.Gov.Ar/ActualizarZonaAustral", RequestNamespace="http://BocaDePago.Anses.Gov.Ar/", ResponseNamespace="http://BocaDePago.Anses.Gov.Ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ActualizarZonaAustral(short id_provincia, short codigopostal, string localidad) {
            object[] results = this.Invoke("ActualizarZonaAustral", new object[] {
                        id_provincia,
                        codigopostal,
                        localidad});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarZonaAustralAsync(short id_provincia, short codigopostal, string localidad) {
            this.ActualizarZonaAustralAsync(id_provincia, codigopostal, localidad, null);
        }
        
        /// <remarks/>
        public void ActualizarZonaAustralAsync(short id_provincia, short codigopostal, string localidad, object userState) {
            if ((this.ActualizarZonaAustralOperationCompleted == null)) {
                this.ActualizarZonaAustralOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarZonaAustralOperationCompleted);
            }
            this.InvokeAsync("ActualizarZonaAustral", new object[] {
                        id_provincia,
                        codigopostal,
                        localidad}, this.ActualizarZonaAustralOperationCompleted, userState);
        }
        
        private void OnActualizarZonaAustralOperationCompleted(object arg) {
            if ((this.ActualizarZonaAustralCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarZonaAustralCompleted(this, new ActualizarZonaAustralCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BocaDePago.Anses.Gov.Ar/")]
    public partial class BeneficioDetalle : Resultado {
        
        private decimal beneficioField;
        
        private string tipoBeneficioField;
        
        private string bancoNombreField;
        
        private string agenciaNombreField;
        
        private short bancoCodigoField;
        
        private short agenciaCodigoField;
        
        private string bancoLocalidadField;
        
        private string bancoDireccionField;
        
        private string cajaField;
        
        private short bancoCodigoPostalField;
        
        private short bancoCodigoProvField;
        
        /// <remarks/>
        public decimal Beneficio {
            get {
                return this.beneficioField;
            }
            set {
                this.beneficioField = value;
            }
        }
        
        /// <remarks/>
        public string TipoBeneficio {
            get {
                return this.tipoBeneficioField;
            }
            set {
                this.tipoBeneficioField = value;
            }
        }
        
        /// <remarks/>
        public string BancoNombre {
            get {
                return this.bancoNombreField;
            }
            set {
                this.bancoNombreField = value;
            }
        }
        
        /// <remarks/>
        public string AgenciaNombre {
            get {
                return this.agenciaNombreField;
            }
            set {
                this.agenciaNombreField = value;
            }
        }
        
        /// <remarks/>
        public short BancoCodigo {
            get {
                return this.bancoCodigoField;
            }
            set {
                this.bancoCodigoField = value;
            }
        }
        
        /// <remarks/>
        public short AgenciaCodigo {
            get {
                return this.agenciaCodigoField;
            }
            set {
                this.agenciaCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string BancoLocalidad {
            get {
                return this.bancoLocalidadField;
            }
            set {
                this.bancoLocalidadField = value;
            }
        }
        
        /// <remarks/>
        public string BancoDireccion {
            get {
                return this.bancoDireccionField;
            }
            set {
                this.bancoDireccionField = value;
            }
        }
        
        /// <remarks/>
        public string Caja {
            get {
                return this.cajaField;
            }
            set {
                this.cajaField = value;
            }
        }
        
        /// <remarks/>
        public short BancoCodigoPostal {
            get {
                return this.bancoCodigoPostalField;
            }
            set {
                this.bancoCodigoPostalField = value;
            }
        }
        
        /// <remarks/>
        public short BancoCodigoProv {
            get {
                return this.bancoCodigoProvField;
            }
            set {
                this.bancoCodigoProvField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DetalleSolicitud))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Provincia))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExCaja))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BeneficioDetalle))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BocaDePago.Anses.Gov.Ar/")]
    public partial class Resultado {
        
        private int errorField;
        
        private string mensajeField;
        
        /// <remarks/>
        public int Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BocaDePago.Anses.Gov.Ar/")]
    public partial class Dependencia {
        
        private long codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        public long Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BocaDePago.Anses.Gov.Ar/")]
    public partial class ZonaAustral {
        
        private int codigoProvinciaField;
        
        private string coberturaField;
        
        private int codigoPostalField;
        
        private string localidadField;
        
        /// <remarks/>
        public int CodigoProvincia {
            get {
                return this.codigoProvinciaField;
            }
            set {
                this.codigoProvinciaField = value;
            }
        }
        
        /// <remarks/>
        public string Cobertura {
            get {
                return this.coberturaField;
            }
            set {
                this.coberturaField = value;
            }
        }
        
        /// <remarks/>
        public int CodigoPostal {
            get {
                return this.codigoPostalField;
            }
            set {
                this.codigoPostalField = value;
            }
        }
        
        /// <remarks/>
        public string Localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BocaDePago.Anses.Gov.Ar/")]
    public partial class BancoAgencia {
        
        private short codigoBancoField;
        
        private short codigoAgenciaField;
        
        private short codigoLocalidadField;
        
        private string bancoField;
        
        private string agenciaField;
        
        private string calleField;
        
        private string numeroField;
        
        private string pisoField;
        
        private string deptoField;
        
        private string localidadField;
        
        private short codigoPostalField;
        
        private short codigoProvinciaField;
        
        /// <remarks/>
        public short CodigoBanco {
            get {
                return this.codigoBancoField;
            }
            set {
                this.codigoBancoField = value;
            }
        }
        
        /// <remarks/>
        public short CodigoAgencia {
            get {
                return this.codigoAgenciaField;
            }
            set {
                this.codigoAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public short CodigoLocalidad {
            get {
                return this.codigoLocalidadField;
            }
            set {
                this.codigoLocalidadField = value;
            }
        }
        
        /// <remarks/>
        public string Banco {
            get {
                return this.bancoField;
            }
            set {
                this.bancoField = value;
            }
        }
        
        /// <remarks/>
        public string Agencia {
            get {
                return this.agenciaField;
            }
            set {
                this.agenciaField = value;
            }
        }
        
        /// <remarks/>
        public string Calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Piso {
            get {
                return this.pisoField;
            }
            set {
                this.pisoField = value;
            }
        }
        
        /// <remarks/>
        public string Depto {
            get {
                return this.deptoField;
            }
            set {
                this.deptoField = value;
            }
        }
        
        /// <remarks/>
        public string Localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
            }
        }
        
        /// <remarks/>
        public short CodigoPostal {
            get {
                return this.codigoPostalField;
            }
            set {
                this.codigoPostalField = value;
            }
        }
        
        /// <remarks/>
        public short CodigoProvincia {
            get {
                return this.codigoProvinciaField;
            }
            set {
                this.codigoProvinciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BocaDePago.Anses.Gov.Ar/")]
    public partial class Confirmacion {
        
        private string mensajeField;
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BocaDePago.Anses.Gov.Ar/")]
    public partial class Novedad {
        
        private short exCajaField;
        
        private short tipoField;
        
        private int numeroField;
        
        private short coparticipeField;
        
        private short codigoMovimientoField;
        
        private short grupoNovedadField;
        
        private string codigoEstadoField;
        
        private long agentePagadorField;
        
        private decimal fechaCargaField;
        
        private int horaField;
        
        private int oficinaField;
        
        private string termidentField;
        
        private string operadorField;
        
        private decimal fechaAProcesarField;
        
        private decimal fechaProcesadaField;
        
        private string textoField;
        
        private decimal cuilBeneficiarioField;
        
        /// <remarks/>
        public short ExCaja {
            get {
                return this.exCajaField;
            }
            set {
                this.exCajaField = value;
            }
        }
        
        /// <remarks/>
        public short Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public short Coparticipe {
            get {
                return this.coparticipeField;
            }
            set {
                this.coparticipeField = value;
            }
        }
        
        /// <remarks/>
        public short CodigoMovimiento {
            get {
                return this.codigoMovimientoField;
            }
            set {
                this.codigoMovimientoField = value;
            }
        }
        
        /// <remarks/>
        public short GrupoNovedad {
            get {
                return this.grupoNovedadField;
            }
            set {
                this.grupoNovedadField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
            }
        }
        
        /// <remarks/>
        public long AgentePagador {
            get {
                return this.agentePagadorField;
            }
            set {
                this.agentePagadorField = value;
            }
        }
        
        /// <remarks/>
        public decimal FechaCarga {
            get {
                return this.fechaCargaField;
            }
            set {
                this.fechaCargaField = value;
            }
        }
        
        /// <remarks/>
        public int Hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
            }
        }
        
        /// <remarks/>
        public int Oficina {
            get {
                return this.oficinaField;
            }
            set {
                this.oficinaField = value;
            }
        }
        
        /// <remarks/>
        public string Termident {
            get {
                return this.termidentField;
            }
            set {
                this.termidentField = value;
            }
        }
        
        /// <remarks/>
        public string Operador {
            get {
                return this.operadorField;
            }
            set {
                this.operadorField = value;
            }
        }
        
        /// <remarks/>
        public decimal FechaAProcesar {
            get {
                return this.fechaAProcesarField;
            }
            set {
                this.fechaAProcesarField = value;
            }
        }
        
        /// <remarks/>
        public decimal FechaProcesada {
            get {
                return this.fechaProcesadaField;
            }
            set {
                this.fechaProcesadaField = value;
            }
        }
        
        /// <remarks/>
        public string Texto {
            get {
                return this.textoField;
            }
            set {
                this.textoField = value;
            }
        }
        
        /// <remarks/>
        public decimal CuilBeneficiario {
            get {
                return this.cuilBeneficiarioField;
            }
            set {
                this.cuilBeneficiarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BocaDePago.Anses.Gov.Ar/")]
    public partial class DetalleSolicitud : Resultado {
        
        private long beneficioField;
        
        private short exCajaField;
        
        private short tipoField;
        
        private int numeroField;
        
        private short coparticipeField;
        
        private short codigoMovimientoField;
        
        private short grupoNovedadField;
        
        private string codigoEstadoField;
        
        private short codigoBancoField;
        
        private short codigoAgenciaField;
        
        private string codigoBancoAgenciaField;
        
        private string bancoField;
        
        private string agenciaField;
        
        private string fechaProcesoField;
        
        private string domCalleField;
        
        private string domNumeroField;
        
        private string domPisoField;
        
        private string domDeptoField;
        
        private string domLocalidadField;
        
        private short domCodigoPostalField;
        
        private short domCodigoProvinciaField;
        
        private string fechaCargaField;
        
        /// <remarks/>
        public long Beneficio {
            get {
                return this.beneficioField;
            }
            set {
                this.beneficioField = value;
            }
        }
        
        /// <remarks/>
        public short ExCaja {
            get {
                return this.exCajaField;
            }
            set {
                this.exCajaField = value;
            }
        }
        
        /// <remarks/>
        public short Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public short Coparticipe {
            get {
                return this.coparticipeField;
            }
            set {
                this.coparticipeField = value;
            }
        }
        
        /// <remarks/>
        public short CodigoMovimiento {
            get {
                return this.codigoMovimientoField;
            }
            set {
                this.codigoMovimientoField = value;
            }
        }
        
        /// <remarks/>
        public short GrupoNovedad {
            get {
                return this.grupoNovedadField;
            }
            set {
                this.grupoNovedadField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
            }
        }
        
        /// <remarks/>
        public short CodigoBanco {
            get {
                return this.codigoBancoField;
            }
            set {
                this.codigoBancoField = value;
            }
        }
        
        /// <remarks/>
        public short CodigoAgencia {
            get {
                return this.codigoAgenciaField;
            }
            set {
                this.codigoAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoBancoAgencia {
            get {
                return this.codigoBancoAgenciaField;
            }
            set {
                this.codigoBancoAgenciaField = value;
            }
        }
        
        /// <remarks/>
        public string Banco {
            get {
                return this.bancoField;
            }
            set {
                this.bancoField = value;
            }
        }
        
        /// <remarks/>
        public string Agencia {
            get {
                return this.agenciaField;
            }
            set {
                this.agenciaField = value;
            }
        }
        
        /// <remarks/>
        public string FechaProceso {
            get {
                return this.fechaProcesoField;
            }
            set {
                this.fechaProcesoField = value;
            }
        }
        
        /// <remarks/>
        public string DomCalle {
            get {
                return this.domCalleField;
            }
            set {
                this.domCalleField = value;
            }
        }
        
        /// <remarks/>
        public string DomNumero {
            get {
                return this.domNumeroField;
            }
            set {
                this.domNumeroField = value;
            }
        }
        
        /// <remarks/>
        public string DomPiso {
            get {
                return this.domPisoField;
            }
            set {
                this.domPisoField = value;
            }
        }
        
        /// <remarks/>
        public string DomDepto {
            get {
                return this.domDeptoField;
            }
            set {
                this.domDeptoField = value;
            }
        }
        
        /// <remarks/>
        public string DomLocalidad {
            get {
                return this.domLocalidadField;
            }
            set {
                this.domLocalidadField = value;
            }
        }
        
        /// <remarks/>
        public short DomCodigoPostal {
            get {
                return this.domCodigoPostalField;
            }
            set {
                this.domCodigoPostalField = value;
            }
        }
        
        /// <remarks/>
        public short DomCodigoProvincia {
            get {
                return this.domCodigoProvinciaField;
            }
            set {
                this.domCodigoProvinciaField = value;
            }
        }
        
        /// <remarks/>
        public string FechaCarga {
            get {
                return this.fechaCargaField;
            }
            set {
                this.fechaCargaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BocaDePago.Anses.Gov.Ar/")]
    public partial class Provincia : Resultado {
        
        private short codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        public short Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://BocaDePago.Anses.Gov.Ar/")]
    public partial class ExCaja : Resultado {
        
        private short codigoField;
        
        private string descrAbreviadaField;
        
        private string descripcionField;
        
        private string codCajaNacionalField;
        
        /// <remarks/>
        public short Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string DescrAbreviada {
            get {
                return this.descrAbreviadaField;
            }
            set {
                this.descrAbreviadaField = value;
            }
        }
        
        /// <remarks/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        public string CodCajaNacional {
            get {
                return this.codCajaNacionalField;
            }
            set {
                this.codCajaNacionalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ObtenerBeneficiosDelCUIPCompletedEventHandler(object sender, ObtenerBeneficiosDelCUIPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerBeneficiosDelCUIPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerBeneficiosDelCUIPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BeneficioDetalle[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BeneficioDetalle[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ObtenerExCajasCompletedEventHandler(object sender, ObtenerExCajasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerExCajasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerExCajasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExCaja[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExCaja[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ObtenerProvinciasCompletedEventHandler(object sender, ObtenerProvinciasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerProvinciasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerProvinciasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Provincia[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Provincia[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ConsultarExistenciaNovedadPendienteCompletedEventHandler(object sender, ConsultarExistenciaNovedadPendienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarExistenciaNovedadPendienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarExistenciaNovedadPendienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Novedad[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Novedad[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ConsultarHistoricoNovedadCompletedEventHandler(object sender, ConsultarHistoricoNovedadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarHistoricoNovedadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarHistoricoNovedadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DetalleSolicitud[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DetalleSolicitud[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GrabarNovedadCompletedEventHandler(object sender, GrabarNovedadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GrabarNovedadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GrabarNovedadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Confirmacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Confirmacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void BajarNovedadCompletedEventHandler(object sender, BajarNovedadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BajarNovedadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BajarNovedadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Confirmacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Confirmacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ModificarNovedadCompletedEventHandler(object sender, ModificarNovedadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificarNovedadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModificarNovedadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Confirmacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Confirmacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ConsultaBancoAgenciaCompletedEventHandler(object sender, ConsultaBancoAgenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaBancoAgenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaBancoAgenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BancoAgencia[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BancoAgencia[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ConsultaDetallesBancoAgenciaCompletedEventHandler(object sender, ConsultaDetallesBancoAgenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaDetallesBancoAgenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaDetallesBancoAgenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BancoAgencia[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BancoAgencia[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ObtenerDetallesBancoAgenciaPorBcoAgeCompletedEventHandler(object sender, ObtenerDetallesBancoAgenciaPorBcoAgeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerDetallesBancoAgenciaPorBcoAgeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerDetallesBancoAgenciaPorBcoAgeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BancoAgencia[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BancoAgencia[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ObtenerZonasAustralesCompletedEventHandler(object sender, ObtenerZonasAustralesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerZonasAustralesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerZonasAustralesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZonaAustral[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZonaAustral[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ObtenerDependenciasHabilitadasCompletedEventHandler(object sender, ObtenerDependenciasHabilitadasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerDependenciasHabilitadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerDependenciasHabilitadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Dependencia[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Dependencia[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ActualizarDependenciaHabilitadaCompletedEventHandler(object sender, ActualizarDependenciaHabilitadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarDependenciaHabilitadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarDependenciaHabilitadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void AgregarDependenciaHabilitadaCompletedEventHandler(object sender, AgregarDependenciaHabilitadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarDependenciaHabilitadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarDependenciaHabilitadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void EliminarDependenciaHabilitadaCompletedEventHandler(object sender, EliminarDependenciaHabilitadaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarDependenciaHabilitadaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarDependenciaHabilitadaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void AgregarZonaAustralCompletedEventHandler(object sender, AgregarZonaAustralCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarZonaAustralCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarZonaAustralCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Nullable<short> Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Nullable<short>)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void EliminarZonaAustralCompletedEventHandler(object sender, EliminarZonaAustralCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarZonaAustralCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarZonaAustralCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ActualizarZonaAustralCompletedEventHandler(object sender, ActualizarZonaAustralCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarZonaAustralCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarZonaAustralCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591