//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Anses.ArgentaC.Negocio.DatosdePersonaporCuip {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DatosdePersonaporCuipSoap", Namespace="http://adp.anses.gov.ar")]
    public partial class DatosdePersonaporCuip : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerPersonaxCUIPOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DatosdePersonaporCuip() {
            this.Url = global::Anses.ArgentaC.Negocio.Properties.Settings.Default.Anses_ArgentaC_Negocio_DatosdePersonaporCuip_DatosdePersonaporCuip;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenerPersonaxCUIPCompletedEventHandler ObtenerPersonaxCUIPCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://adp.anses.gov.ar/ObtenerPersonaxCUIP", RequestNamespace="http://adp.anses.gov.ar", ResponseNamespace="http://adp.anses.gov.ar", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RetornoDatosPersonaCuip ObtenerPersonaxCUIP(string Cuip) {
            object[] results = this.Invoke("ObtenerPersonaxCUIP", new object[] {
                        Cuip});
            return ((RetornoDatosPersonaCuip)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPersonaxCUIPAsync(string Cuip) {
            this.ObtenerPersonaxCUIPAsync(Cuip, null);
        }
        
        /// <remarks/>
        public void ObtenerPersonaxCUIPAsync(string Cuip, object userState) {
            if ((this.ObtenerPersonaxCUIPOperationCompleted == null)) {
                this.ObtenerPersonaxCUIPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPersonaxCUIPOperationCompleted);
            }
            this.InvokeAsync("ObtenerPersonaxCUIP", new object[] {
                        Cuip}, this.ObtenerPersonaxCUIPOperationCompleted, userState);
        }
        
        private void OnObtenerPersonaxCUIPOperationCompleted(object arg) {
            if ((this.ObtenerPersonaxCUIPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPersonaxCUIPCompleted(this, new ObtenerPersonaxCUIPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adp.anses.gov.ar")]
    public partial class RetornoDatosPersonaCuip {
        
        private Error errorField;
        
        private DatosPersonaCuip personaCuipField;
        
        /// <remarks/>
        public Error error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public DatosPersonaCuip PersonaCuip {
            get {
                return this.personaCuipField;
            }
            set {
                this.personaCuipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adp.anses.gov.ar")]
    public partial class Error {
        
        private short cod_retornoField;
        
        private string desc_mensajeField;
        
        private string cod_errorField;
        
        private string cod_gravedadField;
        
        /// <remarks/>
        public short cod_retorno {
            get {
                return this.cod_retornoField;
            }
            set {
                this.cod_retornoField = value;
            }
        }
        
        /// <remarks/>
        public string desc_mensaje {
            get {
                return this.desc_mensajeField;
            }
            set {
                this.desc_mensajeField = value;
            }
        }
        
        /// <remarks/>
        public string cod_error {
            get {
                return this.cod_errorField;
            }
            set {
                this.cod_errorField = value;
            }
        }
        
        /// <remarks/>
        public string cod_gravedad {
            get {
                return this.cod_gravedadField;
            }
            set {
                this.cod_gravedadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adp.anses.gov.ar")]
    public partial class DatosPersonaCuip {
        
        private string cuipField;
        
        private string m_asocField;
        
        private string cuil_anteriorField;
        
        private System.DateTime f_cambioField;
        
        private string tipo_cuipField;
        
        private string apellidoField;
        
        private string nombreField;
        
        private string ape_nomField;
        
        private short doc_c_tipoField;
        
        private short doc_origenField;
        
        private string doc_nroField;
        
        private string doc_copiaField;
        
        private System.DateTime f_naciField;
        
        private string sexoField;
        
        private string cp_marcaField;
        
        private System.DateTime cp_f_desdeField;
        
        private System.DateTime cp_f_hastaField;
        
        private short cp_doc_respField;
        
        private string m_rextrField;
        
        private string t_rextrField;
        
        private System.DateTime f_ing_paisField;
        
        private short cod_comp_ing_paisField;
        
        private short cod_nacionField;
        
        private short cod_estcivilField;
        
        private string lugar_naciField;
        
        private short cod_incapField;
        
        private string m_falleField;
        
        private System.DateTime f_falleField;
        
        private short cod_falleciField;
        
        private System.DateTime f_actu_falleField;
        
        private string usuario_falleField;
        
        private string f_c_orgField;
        
        private string f_pre_cuipField;
        
        private string f_doc_cuipField;
        
        private string f_dig_cuipField;
        
        private string f_c_tipoField;
        
        private string f_c_seqField;
        
        private short f_periodo_mmField;
        
        private short f_periodo_aaField;
        
        private short cod_tipo_domField;
        
        private short cod_comp_domiField;
        
        private System.DateTime f_actu_domiField;
        
        private System.DateTime f_residenciaField;
        
        private string domi_calleField;
        
        private string domi_nroField;
        
        private string domi_pisoField;
        
        private string domi_dptoField;
        
        private short domi_cod_postalField;
        
        private short domi_cod_subpostalField;
        
        private string domi_cod_postal_nuevoField;
        
        private string domi_localidadField;
        
        private short domi_cod_pciaField;
        
        private string domi_anexo_nroField;
        
        private string domi_sectorField;
        
        private string domi_torreField;
        
        private string domi_manzanaField;
        
        private short domi_cod_dat_adicField;
        
        private string domi_dat_adicField;
        
        private string domi_cod_dependenciaField;
        
        private string domi_usuarioField;
        
        private short domi_cod_comp_pais_extrField;
        
        private short domi_cod_pais_extrField;
        
        private string domi_cod_post_extrField;
        
        private short telediscado_paisField;
        
        private int telediscadoField;
        
        private int telefonoField;
        
        private System.DateTime f_actu_telField;
        
        private string cod_dependencia_telField;
        
        private string usuario_telField;
        
        private string marca_celField;
        
        private string emailField;
        
        private short cod_est_grconField;
        
        private short cod_est_enteField;
        
        private string est_e_r_afipField;
        
        private string estado_cuipField;
        
        private string m_doc_robadoField;
        
        private short cod_stma_origenField;
        
        private System.DateTime f_altaField;
        
        private System.DateTime f_ult_modiField;
        
        private System.DateTime h_ult_modiField;
        
        private string c_udaiField;
        
        private string usuarioField;
        
        private short cod_alta_stma_origenField;
        
        private short cod_alta_ente_infField;
        
        private System.DateTime alta_f_altaField;
        
        private string alta_dir_ipField;
        
        private string alta_usuarioField;
        
        private string alta_c_dependenciaField;
        
        private short mod_c_sist_origField;
        
        private short mod_c_ente_infoField;
        
        private string mod_dir_ipField;
        
        private string p_c_orgField;
        
        private string p_pre_cuipField;
        
        private string p_doc_cuipField;
        
        private string p_dig_cuipField;
        
        private string p_c_tipoField;
        
        private string p_c_seqField;
        
        private short p_periodo_mmField;
        
        private short p_periodo_aaField;
        
        private short c_compania_telefonoField;
        
        private short c_pais_origenField;
        
        private short c_ciudadaniaField;
        
        private System.DateTime f_inicio_ciudadaniaField;
        
        private System.DateTime f_vto_ciudadaniaField;
        
        private short c_motivo_ciudadaniaField;
        
        private System.DateTime f_inicio_radicacionField;
        
        private System.DateTime f_vto_radicacionField;
        
        private short c_motivo_radicacionField;
        
        private short c_comprob_ciudadaniaField;
        
        private short c_comprob_radicacionField;
        
        /// <remarks/>
        public string cuip {
            get {
                return this.cuipField;
            }
            set {
                this.cuipField = value;
            }
        }
        
        /// <remarks/>
        public string m_asoc {
            get {
                return this.m_asocField;
            }
            set {
                this.m_asocField = value;
            }
        }
        
        /// <remarks/>
        public string cuil_anterior {
            get {
                return this.cuil_anteriorField;
            }
            set {
                this.cuil_anteriorField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime f_cambio {
            get {
                return this.f_cambioField;
            }
            set {
                this.f_cambioField = value;
            }
        }
        
        /// <remarks/>
        public string tipo_cuip {
            get {
                return this.tipo_cuipField;
            }
            set {
                this.tipo_cuipField = value;
            }
        }
        
        /// <remarks/>
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string ape_nom {
            get {
                return this.ape_nomField;
            }
            set {
                this.ape_nomField = value;
            }
        }
        
        /// <remarks/>
        public short doc_c_tipo {
            get {
                return this.doc_c_tipoField;
            }
            set {
                this.doc_c_tipoField = value;
            }
        }
        
        /// <remarks/>
        public short doc_origen {
            get {
                return this.doc_origenField;
            }
            set {
                this.doc_origenField = value;
            }
        }
        
        /// <remarks/>
        public string doc_nro {
            get {
                return this.doc_nroField;
            }
            set {
                this.doc_nroField = value;
            }
        }
        
        /// <remarks/>
        public string doc_copia {
            get {
                return this.doc_copiaField;
            }
            set {
                this.doc_copiaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime f_naci {
            get {
                return this.f_naciField;
            }
            set {
                this.f_naciField = value;
            }
        }
        
        /// <remarks/>
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        public string cp_marca {
            get {
                return this.cp_marcaField;
            }
            set {
                this.cp_marcaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime cp_f_desde {
            get {
                return this.cp_f_desdeField;
            }
            set {
                this.cp_f_desdeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime cp_f_hasta {
            get {
                return this.cp_f_hastaField;
            }
            set {
                this.cp_f_hastaField = value;
            }
        }
        
        /// <remarks/>
        public short cp_doc_resp {
            get {
                return this.cp_doc_respField;
            }
            set {
                this.cp_doc_respField = value;
            }
        }
        
        /// <remarks/>
        public string m_rextr {
            get {
                return this.m_rextrField;
            }
            set {
                this.m_rextrField = value;
            }
        }
        
        /// <remarks/>
        public string t_rextr {
            get {
                return this.t_rextrField;
            }
            set {
                this.t_rextrField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime f_ing_pais {
            get {
                return this.f_ing_paisField;
            }
            set {
                this.f_ing_paisField = value;
            }
        }
        
        /// <remarks/>
        public short cod_comp_ing_pais {
            get {
                return this.cod_comp_ing_paisField;
            }
            set {
                this.cod_comp_ing_paisField = value;
            }
        }
        
        /// <remarks/>
        public short cod_nacion {
            get {
                return this.cod_nacionField;
            }
            set {
                this.cod_nacionField = value;
            }
        }
        
        /// <remarks/>
        public short cod_estcivil {
            get {
                return this.cod_estcivilField;
            }
            set {
                this.cod_estcivilField = value;
            }
        }
        
        /// <remarks/>
        public string lugar_naci {
            get {
                return this.lugar_naciField;
            }
            set {
                this.lugar_naciField = value;
            }
        }
        
        /// <remarks/>
        public short cod_incap {
            get {
                return this.cod_incapField;
            }
            set {
                this.cod_incapField = value;
            }
        }
        
        /// <remarks/>
        public string m_falle {
            get {
                return this.m_falleField;
            }
            set {
                this.m_falleField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime f_falle {
            get {
                return this.f_falleField;
            }
            set {
                this.f_falleField = value;
            }
        }
        
        /// <remarks/>
        public short cod_falleci {
            get {
                return this.cod_falleciField;
            }
            set {
                this.cod_falleciField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime f_actu_falle {
            get {
                return this.f_actu_falleField;
            }
            set {
                this.f_actu_falleField = value;
            }
        }
        
        /// <remarks/>
        public string usuario_falle {
            get {
                return this.usuario_falleField;
            }
            set {
                this.usuario_falleField = value;
            }
        }
        
        /// <remarks/>
        public string f_c_org {
            get {
                return this.f_c_orgField;
            }
            set {
                this.f_c_orgField = value;
            }
        }
        
        /// <remarks/>
        public string f_pre_cuip {
            get {
                return this.f_pre_cuipField;
            }
            set {
                this.f_pre_cuipField = value;
            }
        }
        
        /// <remarks/>
        public string f_doc_cuip {
            get {
                return this.f_doc_cuipField;
            }
            set {
                this.f_doc_cuipField = value;
            }
        }
        
        /// <remarks/>
        public string f_dig_cuip {
            get {
                return this.f_dig_cuipField;
            }
            set {
                this.f_dig_cuipField = value;
            }
        }
        
        /// <remarks/>
        public string f_c_tipo {
            get {
                return this.f_c_tipoField;
            }
            set {
                this.f_c_tipoField = value;
            }
        }
        
        /// <remarks/>
        public string f_c_seq {
            get {
                return this.f_c_seqField;
            }
            set {
                this.f_c_seqField = value;
            }
        }
        
        /// <remarks/>
        public short f_periodo_mm {
            get {
                return this.f_periodo_mmField;
            }
            set {
                this.f_periodo_mmField = value;
            }
        }
        
        /// <remarks/>
        public short f_periodo_aa {
            get {
                return this.f_periodo_aaField;
            }
            set {
                this.f_periodo_aaField = value;
            }
        }
        
        /// <remarks/>
        public short cod_tipo_dom {
            get {
                return this.cod_tipo_domField;
            }
            set {
                this.cod_tipo_domField = value;
            }
        }
        
        /// <remarks/>
        public short cod_comp_domi {
            get {
                return this.cod_comp_domiField;
            }
            set {
                this.cod_comp_domiField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime f_actu_domi {
            get {
                return this.f_actu_domiField;
            }
            set {
                this.f_actu_domiField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime f_residencia {
            get {
                return this.f_residenciaField;
            }
            set {
                this.f_residenciaField = value;
            }
        }
        
        /// <remarks/>
        public string domi_calle {
            get {
                return this.domi_calleField;
            }
            set {
                this.domi_calleField = value;
            }
        }
        
        /// <remarks/>
        public string domi_nro {
            get {
                return this.domi_nroField;
            }
            set {
                this.domi_nroField = value;
            }
        }
        
        /// <remarks/>
        public string domi_piso {
            get {
                return this.domi_pisoField;
            }
            set {
                this.domi_pisoField = value;
            }
        }
        
        /// <remarks/>
        public string domi_dpto {
            get {
                return this.domi_dptoField;
            }
            set {
                this.domi_dptoField = value;
            }
        }
        
        /// <remarks/>
        public short domi_cod_postal {
            get {
                return this.domi_cod_postalField;
            }
            set {
                this.domi_cod_postalField = value;
            }
        }
        
        /// <remarks/>
        public short domi_cod_subpostal {
            get {
                return this.domi_cod_subpostalField;
            }
            set {
                this.domi_cod_subpostalField = value;
            }
        }
        
        /// <remarks/>
        public string domi_cod_postal_nuevo {
            get {
                return this.domi_cod_postal_nuevoField;
            }
            set {
                this.domi_cod_postal_nuevoField = value;
            }
        }
        
        /// <remarks/>
        public string domi_localidad {
            get {
                return this.domi_localidadField;
            }
            set {
                this.domi_localidadField = value;
            }
        }
        
        /// <remarks/>
        public short domi_cod_pcia {
            get {
                return this.domi_cod_pciaField;
            }
            set {
                this.domi_cod_pciaField = value;
            }
        }
        
        /// <remarks/>
        public string domi_anexo_nro {
            get {
                return this.domi_anexo_nroField;
            }
            set {
                this.domi_anexo_nroField = value;
            }
        }
        
        /// <remarks/>
        public string domi_sector {
            get {
                return this.domi_sectorField;
            }
            set {
                this.domi_sectorField = value;
            }
        }
        
        /// <remarks/>
        public string domi_torre {
            get {
                return this.domi_torreField;
            }
            set {
                this.domi_torreField = value;
            }
        }
        
        /// <remarks/>
        public string domi_manzana {
            get {
                return this.domi_manzanaField;
            }
            set {
                this.domi_manzanaField = value;
            }
        }
        
        /// <remarks/>
        public short domi_cod_dat_adic {
            get {
                return this.domi_cod_dat_adicField;
            }
            set {
                this.domi_cod_dat_adicField = value;
            }
        }
        
        /// <remarks/>
        public string domi_dat_adic {
            get {
                return this.domi_dat_adicField;
            }
            set {
                this.domi_dat_adicField = value;
            }
        }
        
        /// <remarks/>
        public string domi_cod_dependencia {
            get {
                return this.domi_cod_dependenciaField;
            }
            set {
                this.domi_cod_dependenciaField = value;
            }
        }
        
        /// <remarks/>
        public string domi_usuario {
            get {
                return this.domi_usuarioField;
            }
            set {
                this.domi_usuarioField = value;
            }
        }
        
        /// <remarks/>
        public short domi_cod_comp_pais_extr {
            get {
                return this.domi_cod_comp_pais_extrField;
            }
            set {
                this.domi_cod_comp_pais_extrField = value;
            }
        }
        
        /// <remarks/>
        public short domi_cod_pais_extr {
            get {
                return this.domi_cod_pais_extrField;
            }
            set {
                this.domi_cod_pais_extrField = value;
            }
        }
        
        /// <remarks/>
        public string domi_cod_post_extr {
            get {
                return this.domi_cod_post_extrField;
            }
            set {
                this.domi_cod_post_extrField = value;
            }
        }
        
        /// <remarks/>
        public short telediscado_pais {
            get {
                return this.telediscado_paisField;
            }
            set {
                this.telediscado_paisField = value;
            }
        }
        
        /// <remarks/>
        public int telediscado {
            get {
                return this.telediscadoField;
            }
            set {
                this.telediscadoField = value;
            }
        }
        
        /// <remarks/>
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime f_actu_tel {
            get {
                return this.f_actu_telField;
            }
            set {
                this.f_actu_telField = value;
            }
        }
        
        /// <remarks/>
        public string cod_dependencia_tel {
            get {
                return this.cod_dependencia_telField;
            }
            set {
                this.cod_dependencia_telField = value;
            }
        }
        
        /// <remarks/>
        public string usuario_tel {
            get {
                return this.usuario_telField;
            }
            set {
                this.usuario_telField = value;
            }
        }
        
        /// <remarks/>
        public string marca_cel {
            get {
                return this.marca_celField;
            }
            set {
                this.marca_celField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public short cod_est_grcon {
            get {
                return this.cod_est_grconField;
            }
            set {
                this.cod_est_grconField = value;
            }
        }
        
        /// <remarks/>
        public short cod_est_ente {
            get {
                return this.cod_est_enteField;
            }
            set {
                this.cod_est_enteField = value;
            }
        }
        
        /// <remarks/>
        public string est_e_r_afip {
            get {
                return this.est_e_r_afipField;
            }
            set {
                this.est_e_r_afipField = value;
            }
        }
        
        /// <remarks/>
        public string estado_cuip {
            get {
                return this.estado_cuipField;
            }
            set {
                this.estado_cuipField = value;
            }
        }
        
        /// <remarks/>
        public string m_doc_robado {
            get {
                return this.m_doc_robadoField;
            }
            set {
                this.m_doc_robadoField = value;
            }
        }
        
        /// <remarks/>
        public short cod_stma_origen {
            get {
                return this.cod_stma_origenField;
            }
            set {
                this.cod_stma_origenField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime f_alta {
            get {
                return this.f_altaField;
            }
            set {
                this.f_altaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime f_ult_modi {
            get {
                return this.f_ult_modiField;
            }
            set {
                this.f_ult_modiField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime h_ult_modi {
            get {
                return this.h_ult_modiField;
            }
            set {
                this.h_ult_modiField = value;
            }
        }
        
        /// <remarks/>
        public string c_udai {
            get {
                return this.c_udaiField;
            }
            set {
                this.c_udaiField = value;
            }
        }
        
        /// <remarks/>
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public short cod_alta_stma_origen {
            get {
                return this.cod_alta_stma_origenField;
            }
            set {
                this.cod_alta_stma_origenField = value;
            }
        }
        
        /// <remarks/>
        public short cod_alta_ente_inf {
            get {
                return this.cod_alta_ente_infField;
            }
            set {
                this.cod_alta_ente_infField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime alta_f_alta {
            get {
                return this.alta_f_altaField;
            }
            set {
                this.alta_f_altaField = value;
            }
        }
        
        /// <remarks/>
        public string alta_dir_ip {
            get {
                return this.alta_dir_ipField;
            }
            set {
                this.alta_dir_ipField = value;
            }
        }
        
        /// <remarks/>
        public string alta_usuario {
            get {
                return this.alta_usuarioField;
            }
            set {
                this.alta_usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string alta_c_dependencia {
            get {
                return this.alta_c_dependenciaField;
            }
            set {
                this.alta_c_dependenciaField = value;
            }
        }
        
        /// <remarks/>
        public short mod_c_sist_orig {
            get {
                return this.mod_c_sist_origField;
            }
            set {
                this.mod_c_sist_origField = value;
            }
        }
        
        /// <remarks/>
        public short mod_c_ente_info {
            get {
                return this.mod_c_ente_infoField;
            }
            set {
                this.mod_c_ente_infoField = value;
            }
        }
        
        /// <remarks/>
        public string mod_dir_ip {
            get {
                return this.mod_dir_ipField;
            }
            set {
                this.mod_dir_ipField = value;
            }
        }
        
        /// <remarks/>
        public string p_c_org {
            get {
                return this.p_c_orgField;
            }
            set {
                this.p_c_orgField = value;
            }
        }
        
        /// <remarks/>
        public string p_pre_cuip {
            get {
                return this.p_pre_cuipField;
            }
            set {
                this.p_pre_cuipField = value;
            }
        }
        
        /// <remarks/>
        public string p_doc_cuip {
            get {
                return this.p_doc_cuipField;
            }
            set {
                this.p_doc_cuipField = value;
            }
        }
        
        /// <remarks/>
        public string p_dig_cuip {
            get {
                return this.p_dig_cuipField;
            }
            set {
                this.p_dig_cuipField = value;
            }
        }
        
        /// <remarks/>
        public string p_c_tipo {
            get {
                return this.p_c_tipoField;
            }
            set {
                this.p_c_tipoField = value;
            }
        }
        
        /// <remarks/>
        public string p_c_seq {
            get {
                return this.p_c_seqField;
            }
            set {
                this.p_c_seqField = value;
            }
        }
        
        /// <remarks/>
        public short p_periodo_mm {
            get {
                return this.p_periodo_mmField;
            }
            set {
                this.p_periodo_mmField = value;
            }
        }
        
        /// <remarks/>
        public short p_periodo_aa {
            get {
                return this.p_periodo_aaField;
            }
            set {
                this.p_periodo_aaField = value;
            }
        }
        
        /// <remarks/>
        public short c_compania_telefono {
            get {
                return this.c_compania_telefonoField;
            }
            set {
                this.c_compania_telefonoField = value;
            }
        }
        
        /// <remarks/>
        public short c_pais_origen {
            get {
                return this.c_pais_origenField;
            }
            set {
                this.c_pais_origenField = value;
            }
        }
        
        /// <remarks/>
        public short c_ciudadania {
            get {
                return this.c_ciudadaniaField;
            }
            set {
                this.c_ciudadaniaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime f_inicio_ciudadania {
            get {
                return this.f_inicio_ciudadaniaField;
            }
            set {
                this.f_inicio_ciudadaniaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime f_vto_ciudadania {
            get {
                return this.f_vto_ciudadaniaField;
            }
            set {
                this.f_vto_ciudadaniaField = value;
            }
        }
        
        /// <remarks/>
        public short c_motivo_ciudadania {
            get {
                return this.c_motivo_ciudadaniaField;
            }
            set {
                this.c_motivo_ciudadaniaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime f_inicio_radicacion {
            get {
                return this.f_inicio_radicacionField;
            }
            set {
                this.f_inicio_radicacionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime f_vto_radicacion {
            get {
                return this.f_vto_radicacionField;
            }
            set {
                this.f_vto_radicacionField = value;
            }
        }
        
        /// <remarks/>
        public short c_motivo_radicacion {
            get {
                return this.c_motivo_radicacionField;
            }
            set {
                this.c_motivo_radicacionField = value;
            }
        }
        
        /// <remarks/>
        public short c_comprob_ciudadania {
            get {
                return this.c_comprob_ciudadaniaField;
            }
            set {
                this.c_comprob_ciudadaniaField = value;
            }
        }
        
        /// <remarks/>
        public short c_comprob_radicacion {
            get {
                return this.c_comprob_radicacionField;
            }
            set {
                this.c_comprob_radicacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ObtenerPersonaxCUIPCompletedEventHandler(object sender, ObtenerPersonaxCUIPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPersonaxCUIPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPersonaxCUIPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetornoDatosPersonaCuip Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetornoDatosPersonaCuip)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591