//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Anses.ArgentaC.Negocio.ExpedienteWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ExpedienteWSSoap", Namespace="http://anses.gov.ar/anme/")]
    public partial class ExpedienteWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuscarExpedientesPorCuilOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarExpedientesPorCuilYTiposDeTramitesOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarExpedientesPorOrganismoYCuilYTiposDeTramitesOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarExpedientesPorTipoyNumeroDeDocumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarExpedientesPorCuilYTipoyNumeroDeDocumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarExpedienteDetalladoPorPKOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarExpedientesPorBeneficioParaRHOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaExpedientesPorCuilListaGrupEstadisticoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ExpedienteWS() {
            this.Url = global::Anses.ArgentaC.Negocio.Properties.Settings.Default.Anses_ArgentaC_Negocio_ExpedienteWS_ExpedienteWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuscarExpedientesPorCuilCompletedEventHandler BuscarExpedientesPorCuilCompleted;
        
        /// <remarks/>
        public event BuscarExpedientesPorCuilYTiposDeTramitesCompletedEventHandler BuscarExpedientesPorCuilYTiposDeTramitesCompleted;
        
        /// <remarks/>
        public event BuscarExpedientesPorOrganismoYCuilYTiposDeTramitesCompletedEventHandler BuscarExpedientesPorOrganismoYCuilYTiposDeTramitesCompleted;
        
        /// <remarks/>
        public event BuscarExpedientesPorTipoyNumeroDeDocumentoCompletedEventHandler BuscarExpedientesPorTipoyNumeroDeDocumentoCompleted;
        
        /// <remarks/>
        public event BuscarExpedientesPorCuilYTipoyNumeroDeDocumentoCompletedEventHandler BuscarExpedientesPorCuilYTipoyNumeroDeDocumentoCompleted;
        
        /// <remarks/>
        public event BuscarExpedienteDetalladoPorPKCompletedEventHandler BuscarExpedienteDetalladoPorPKCompleted;
        
        /// <remarks/>
        public event BuscarExpedientesPorBeneficioParaRHCompletedEventHandler BuscarExpedientesPorBeneficioParaRHCompleted;
        
        /// <remarks/>
        public event ConsultaExpedientesPorCuilListaGrupEstadisticoCompletedEventHandler ConsultaExpedientesPorCuilListaGrupEstadisticoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://anses.gov.ar/anme/BuscarExpedientesPorCuil", RequestNamespace="http://anses.gov.ar/anme/", ResponseNamespace="http://anses.gov.ar/anme/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExpedienteDTO[] BuscarExpedientesPorCuil(CuilDTO cuilDTO, out TipoError error) {
            object[] results = this.Invoke("BuscarExpedientesPorCuil", new object[] {
                        cuilDTO});
            error = ((TipoError)(results[1]));
            return ((ExpedienteDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarExpedientesPorCuilAsync(CuilDTO cuilDTO) {
            this.BuscarExpedientesPorCuilAsync(cuilDTO, null);
        }
        
        /// <remarks/>
        public void BuscarExpedientesPorCuilAsync(CuilDTO cuilDTO, object userState) {
            if ((this.BuscarExpedientesPorCuilOperationCompleted == null)) {
                this.BuscarExpedientesPorCuilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarExpedientesPorCuilOperationCompleted);
            }
            this.InvokeAsync("BuscarExpedientesPorCuil", new object[] {
                        cuilDTO}, this.BuscarExpedientesPorCuilOperationCompleted, userState);
        }
        
        private void OnBuscarExpedientesPorCuilOperationCompleted(object arg) {
            if ((this.BuscarExpedientesPorCuilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarExpedientesPorCuilCompleted(this, new BuscarExpedientesPorCuilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://anses.gov.ar/anme/BuscarExpedientesPorCuilYTiposDeTramites", RequestNamespace="http://anses.gov.ar/anme/", ResponseNamespace="http://anses.gov.ar/anme/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExpedienteDTO[] BuscarExpedientesPorCuilYTiposDeTramites(CuilDTO cuilDTO, string TiposDeTramites, out TipoError error) {
            object[] results = this.Invoke("BuscarExpedientesPorCuilYTiposDeTramites", new object[] {
                        cuilDTO,
                        TiposDeTramites});
            error = ((TipoError)(results[1]));
            return ((ExpedienteDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarExpedientesPorCuilYTiposDeTramitesAsync(CuilDTO cuilDTO, string TiposDeTramites) {
            this.BuscarExpedientesPorCuilYTiposDeTramitesAsync(cuilDTO, TiposDeTramites, null);
        }
        
        /// <remarks/>
        public void BuscarExpedientesPorCuilYTiposDeTramitesAsync(CuilDTO cuilDTO, string TiposDeTramites, object userState) {
            if ((this.BuscarExpedientesPorCuilYTiposDeTramitesOperationCompleted == null)) {
                this.BuscarExpedientesPorCuilYTiposDeTramitesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarExpedientesPorCuilYTiposDeTramitesOperationCompleted);
            }
            this.InvokeAsync("BuscarExpedientesPorCuilYTiposDeTramites", new object[] {
                        cuilDTO,
                        TiposDeTramites}, this.BuscarExpedientesPorCuilYTiposDeTramitesOperationCompleted, userState);
        }
        
        private void OnBuscarExpedientesPorCuilYTiposDeTramitesOperationCompleted(object arg) {
            if ((this.BuscarExpedientesPorCuilYTiposDeTramitesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarExpedientesPorCuilYTiposDeTramitesCompleted(this, new BuscarExpedientesPorCuilYTiposDeTramitesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://anses.gov.ar/anme/BuscarExpedientesPorOrganismoYCuilYTiposDeTramites", RequestNamespace="http://anses.gov.ar/anme/", ResponseNamespace="http://anses.gov.ar/anme/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExpedienteDTO[] BuscarExpedientesPorOrganismoYCuilYTiposDeTramites(string organismo, CuilDTO cuilDTO, string TiposDeTramites, out TipoError error) {
            object[] results = this.Invoke("BuscarExpedientesPorOrganismoYCuilYTiposDeTramites", new object[] {
                        organismo,
                        cuilDTO,
                        TiposDeTramites});
            error = ((TipoError)(results[1]));
            return ((ExpedienteDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarExpedientesPorOrganismoYCuilYTiposDeTramitesAsync(string organismo, CuilDTO cuilDTO, string TiposDeTramites) {
            this.BuscarExpedientesPorOrganismoYCuilYTiposDeTramitesAsync(organismo, cuilDTO, TiposDeTramites, null);
        }
        
        /// <remarks/>
        public void BuscarExpedientesPorOrganismoYCuilYTiposDeTramitesAsync(string organismo, CuilDTO cuilDTO, string TiposDeTramites, object userState) {
            if ((this.BuscarExpedientesPorOrganismoYCuilYTiposDeTramitesOperationCompleted == null)) {
                this.BuscarExpedientesPorOrganismoYCuilYTiposDeTramitesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarExpedientesPorOrganismoYCuilYTiposDeTramitesOperationCompleted);
            }
            this.InvokeAsync("BuscarExpedientesPorOrganismoYCuilYTiposDeTramites", new object[] {
                        organismo,
                        cuilDTO,
                        TiposDeTramites}, this.BuscarExpedientesPorOrganismoYCuilYTiposDeTramitesOperationCompleted, userState);
        }
        
        private void OnBuscarExpedientesPorOrganismoYCuilYTiposDeTramitesOperationCompleted(object arg) {
            if ((this.BuscarExpedientesPorOrganismoYCuilYTiposDeTramitesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarExpedientesPorOrganismoYCuilYTiposDeTramitesCompleted(this, new BuscarExpedientesPorOrganismoYCuilYTiposDeTramitesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://anses.gov.ar/anme/BuscarExpedientesPorTipoyNumeroDeDocumento", RequestNamespace="http://anses.gov.ar/anme/", ResponseNamespace="http://anses.gov.ar/anme/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExpedienteDTO[] BuscarExpedientesPorTipoyNumeroDeDocumento(string tipoDocumento, string numeroDocumento, out TipoError error) {
            object[] results = this.Invoke("BuscarExpedientesPorTipoyNumeroDeDocumento", new object[] {
                        tipoDocumento,
                        numeroDocumento});
            error = ((TipoError)(results[1]));
            return ((ExpedienteDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarExpedientesPorTipoyNumeroDeDocumentoAsync(string tipoDocumento, string numeroDocumento) {
            this.BuscarExpedientesPorTipoyNumeroDeDocumentoAsync(tipoDocumento, numeroDocumento, null);
        }
        
        /// <remarks/>
        public void BuscarExpedientesPorTipoyNumeroDeDocumentoAsync(string tipoDocumento, string numeroDocumento, object userState) {
            if ((this.BuscarExpedientesPorTipoyNumeroDeDocumentoOperationCompleted == null)) {
                this.BuscarExpedientesPorTipoyNumeroDeDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarExpedientesPorTipoyNumeroDeDocumentoOperationCompleted);
            }
            this.InvokeAsync("BuscarExpedientesPorTipoyNumeroDeDocumento", new object[] {
                        tipoDocumento,
                        numeroDocumento}, this.BuscarExpedientesPorTipoyNumeroDeDocumentoOperationCompleted, userState);
        }
        
        private void OnBuscarExpedientesPorTipoyNumeroDeDocumentoOperationCompleted(object arg) {
            if ((this.BuscarExpedientesPorTipoyNumeroDeDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarExpedientesPorTipoyNumeroDeDocumentoCompleted(this, new BuscarExpedientesPorTipoyNumeroDeDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://anses.gov.ar/anme/BuscarExpedientesPorCuilYTipoyNumeroDeDocumento", RequestNamespace="http://anses.gov.ar/anme/", ResponseNamespace="http://anses.gov.ar/anme/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExpedienteDTO[] BuscarExpedientesPorCuilYTipoyNumeroDeDocumento(CuilDTO cuilDTO, out TipoError error) {
            object[] results = this.Invoke("BuscarExpedientesPorCuilYTipoyNumeroDeDocumento", new object[] {
                        cuilDTO});
            error = ((TipoError)(results[1]));
            return ((ExpedienteDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarExpedientesPorCuilYTipoyNumeroDeDocumentoAsync(CuilDTO cuilDTO) {
            this.BuscarExpedientesPorCuilYTipoyNumeroDeDocumentoAsync(cuilDTO, null);
        }
        
        /// <remarks/>
        public void BuscarExpedientesPorCuilYTipoyNumeroDeDocumentoAsync(CuilDTO cuilDTO, object userState) {
            if ((this.BuscarExpedientesPorCuilYTipoyNumeroDeDocumentoOperationCompleted == null)) {
                this.BuscarExpedientesPorCuilYTipoyNumeroDeDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarExpedientesPorCuilYTipoyNumeroDeDocumentoOperationCompleted);
            }
            this.InvokeAsync("BuscarExpedientesPorCuilYTipoyNumeroDeDocumento", new object[] {
                        cuilDTO}, this.BuscarExpedientesPorCuilYTipoyNumeroDeDocumentoOperationCompleted, userState);
        }
        
        private void OnBuscarExpedientesPorCuilYTipoyNumeroDeDocumentoOperationCompleted(object arg) {
            if ((this.BuscarExpedientesPorCuilYTipoyNumeroDeDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarExpedientesPorCuilYTipoyNumeroDeDocumentoCompleted(this, new BuscarExpedientesPorCuilYTipoyNumeroDeDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://anses.gov.ar/anme/BuscarExpedienteDetalladoPorPK", RequestNamespace="http://anses.gov.ar/anme/", ResponseNamespace="http://anses.gov.ar/anme/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExpedienteDetalladoDTO BuscarExpedienteDetalladoPorPK(ExpedienteIdDTO expediente, out TipoError error) {
            object[] results = this.Invoke("BuscarExpedienteDetalladoPorPK", new object[] {
                        expediente});
            error = ((TipoError)(results[1]));
            return ((ExpedienteDetalladoDTO)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarExpedienteDetalladoPorPKAsync(ExpedienteIdDTO expediente) {
            this.BuscarExpedienteDetalladoPorPKAsync(expediente, null);
        }
        
        /// <remarks/>
        public void BuscarExpedienteDetalladoPorPKAsync(ExpedienteIdDTO expediente, object userState) {
            if ((this.BuscarExpedienteDetalladoPorPKOperationCompleted == null)) {
                this.BuscarExpedienteDetalladoPorPKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarExpedienteDetalladoPorPKOperationCompleted);
            }
            this.InvokeAsync("BuscarExpedienteDetalladoPorPK", new object[] {
                        expediente}, this.BuscarExpedienteDetalladoPorPKOperationCompleted, userState);
        }
        
        private void OnBuscarExpedienteDetalladoPorPKOperationCompleted(object arg) {
            if ((this.BuscarExpedienteDetalladoPorPKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarExpedienteDetalladoPorPKCompleted(this, new BuscarExpedienteDetalladoPorPKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://anses.gov.ar/anme/BuscarExpedientesPorBeneficioParaRH", RequestNamespace="http://anses.gov.ar/anme/", ResponseNamespace="http://anses.gov.ar/anme/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExpedientePorBeneficioRHDTO[] BuscarExpedientesPorBeneficioParaRH(string exCajaBeneficio, string tipoBeneficio, string beneficioNro, string coparticipeBeneficio, out TipoError error) {
            object[] results = this.Invoke("BuscarExpedientesPorBeneficioParaRH", new object[] {
                        exCajaBeneficio,
                        tipoBeneficio,
                        beneficioNro,
                        coparticipeBeneficio});
            error = ((TipoError)(results[1]));
            return ((ExpedientePorBeneficioRHDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarExpedientesPorBeneficioParaRHAsync(string exCajaBeneficio, string tipoBeneficio, string beneficioNro, string coparticipeBeneficio) {
            this.BuscarExpedientesPorBeneficioParaRHAsync(exCajaBeneficio, tipoBeneficio, beneficioNro, coparticipeBeneficio, null);
        }
        
        /// <remarks/>
        public void BuscarExpedientesPorBeneficioParaRHAsync(string exCajaBeneficio, string tipoBeneficio, string beneficioNro, string coparticipeBeneficio, object userState) {
            if ((this.BuscarExpedientesPorBeneficioParaRHOperationCompleted == null)) {
                this.BuscarExpedientesPorBeneficioParaRHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarExpedientesPorBeneficioParaRHOperationCompleted);
            }
            this.InvokeAsync("BuscarExpedientesPorBeneficioParaRH", new object[] {
                        exCajaBeneficio,
                        tipoBeneficio,
                        beneficioNro,
                        coparticipeBeneficio}, this.BuscarExpedientesPorBeneficioParaRHOperationCompleted, userState);
        }
        
        private void OnBuscarExpedientesPorBeneficioParaRHOperationCompleted(object arg) {
            if ((this.BuscarExpedientesPorBeneficioParaRHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarExpedientesPorBeneficioParaRHCompleted(this, new BuscarExpedientesPorBeneficioParaRHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://anses.gov.ar/anme/ConsultaExpedientesPorCuilListaGrupEstadistico", RequestNamespace="http://anses.gov.ar/anme/", ResponseNamespace="http://anses.gov.ar/anme/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExpedienteDTO[] ConsultaExpedientesPorCuilListaGrupEstadistico(CuilDTO cuilDTO, string cGgrupoEstad, out TipoError error) {
            object[] results = this.Invoke("ConsultaExpedientesPorCuilListaGrupEstadistico", new object[] {
                        cuilDTO,
                        cGgrupoEstad});
            error = ((TipoError)(results[1]));
            return ((ExpedienteDTO[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaExpedientesPorCuilListaGrupEstadisticoAsync(CuilDTO cuilDTO, string cGgrupoEstad) {
            this.ConsultaExpedientesPorCuilListaGrupEstadisticoAsync(cuilDTO, cGgrupoEstad, null);
        }
        
        /// <remarks/>
        public void ConsultaExpedientesPorCuilListaGrupEstadisticoAsync(CuilDTO cuilDTO, string cGgrupoEstad, object userState) {
            if ((this.ConsultaExpedientesPorCuilListaGrupEstadisticoOperationCompleted == null)) {
                this.ConsultaExpedientesPorCuilListaGrupEstadisticoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaExpedientesPorCuilListaGrupEstadisticoOperationCompleted);
            }
            this.InvokeAsync("ConsultaExpedientesPorCuilListaGrupEstadistico", new object[] {
                        cuilDTO,
                        cGgrupoEstad}, this.ConsultaExpedientesPorCuilListaGrupEstadisticoOperationCompleted, userState);
        }
        
        private void OnConsultaExpedientesPorCuilListaGrupEstadisticoOperationCompleted(object arg) {
            if ((this.ConsultaExpedientesPorCuilListaGrupEstadisticoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaExpedientesPorCuilListaGrupEstadisticoCompleted(this, new ConsultaExpedientesPorCuilListaGrupEstadisticoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anses.gov.ar/anme/")]
    public partial class CuilDTO {
        
        private string preCuilField;
        
        private string docCuilField;
        
        private string digCuilField;
        
        /// <remarks/>
        public string preCuil {
            get {
                return this.preCuilField;
            }
            set {
                this.preCuilField = value;
            }
        }
        
        /// <remarks/>
        public string docCuil {
            get {
                return this.docCuilField;
            }
            set {
                this.docCuilField = value;
            }
        }
        
        /// <remarks/>
        public string digCuil {
            get {
                return this.digCuilField;
            }
            set {
                this.digCuilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anses.gov.ar/anme/")]
    public partial class ExpedientePorBeneficioRHDTO {
        
        private string organismoField;
        
        private string preCuilField;
        
        private string docCuilField;
        
        private string digCuilField;
        
        private string tipoTramiteField;
        
        private string secuenciaField;
        
        private string estadoField;
        
        private string caratulaField;
        
        private System.DateTime beneficioFacuField;
        
        private string beneficioExCajaField;
        
        private string beneficioTipoField;
        
        private string beneficioNumeroField;
        
        private string beneficioCoparticipeField;
        
        private string usuarioAltaField;
        
        private string ultimaOficinaField;
        
        private System.Nullable<System.DateTime> fechaInicioAFJPField;
        
        private System.DateTime fechaActualizacionField;
        
        private string codigoOficinaAltaField;
        
        private System.Nullable<System.DateTime> fechaAltaField;
        
        private System.Nullable<System.DateTime> fechaEstadoField;
        
        /// <remarks/>
        public string organismo {
            get {
                return this.organismoField;
            }
            set {
                this.organismoField = value;
            }
        }
        
        /// <remarks/>
        public string preCuil {
            get {
                return this.preCuilField;
            }
            set {
                this.preCuilField = value;
            }
        }
        
        /// <remarks/>
        public string docCuil {
            get {
                return this.docCuilField;
            }
            set {
                this.docCuilField = value;
            }
        }
        
        /// <remarks/>
        public string digCuil {
            get {
                return this.digCuilField;
            }
            set {
                this.digCuilField = value;
            }
        }
        
        /// <remarks/>
        public string tipoTramite {
            get {
                return this.tipoTramiteField;
            }
            set {
                this.tipoTramiteField = value;
            }
        }
        
        /// <remarks/>
        public string secuencia {
            get {
                return this.secuenciaField;
            }
            set {
                this.secuenciaField = value;
            }
        }
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string caratula {
            get {
                return this.caratulaField;
            }
            set {
                this.caratulaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime beneficioFacu {
            get {
                return this.beneficioFacuField;
            }
            set {
                this.beneficioFacuField = value;
            }
        }
        
        /// <remarks/>
        public string beneficioExCaja {
            get {
                return this.beneficioExCajaField;
            }
            set {
                this.beneficioExCajaField = value;
            }
        }
        
        /// <remarks/>
        public string beneficioTipo {
            get {
                return this.beneficioTipoField;
            }
            set {
                this.beneficioTipoField = value;
            }
        }
        
        /// <remarks/>
        public string beneficioNumero {
            get {
                return this.beneficioNumeroField;
            }
            set {
                this.beneficioNumeroField = value;
            }
        }
        
        /// <remarks/>
        public string beneficioCoparticipe {
            get {
                return this.beneficioCoparticipeField;
            }
            set {
                this.beneficioCoparticipeField = value;
            }
        }
        
        /// <remarks/>
        public string usuarioAlta {
            get {
                return this.usuarioAltaField;
            }
            set {
                this.usuarioAltaField = value;
            }
        }
        
        /// <remarks/>
        public string ultimaOficina {
            get {
                return this.ultimaOficinaField;
            }
            set {
                this.ultimaOficinaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechaInicioAFJP {
            get {
                return this.fechaInicioAFJPField;
            }
            set {
                this.fechaInicioAFJPField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
            }
        }
        
        /// <remarks/>
        public string codigoOficinaAlta {
            get {
                return this.codigoOficinaAltaField;
            }
            set {
                this.codigoOficinaAltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechaAlta {
            get {
                return this.fechaAltaField;
            }
            set {
                this.fechaAltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechaEstado {
            get {
                return this.fechaEstadoField;
            }
            set {
                this.fechaEstadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anses.gov.ar/anme/")]
    public partial class MatriculaAbogadoDTO {
        
        private string colegioField;
        
        private string folioField;
        
        private string tomoField;
        
        /// <remarks/>
        public string colegio {
            get {
                return this.colegioField;
            }
            set {
                this.colegioField = value;
            }
        }
        
        /// <remarks/>
        public string folio {
            get {
                return this.folioField;
            }
            set {
                this.folioField = value;
            }
        }
        
        /// <remarks/>
        public string tomo {
            get {
                return this.tomoField;
            }
            set {
                this.tomoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anses.gov.ar/anme/")]
    public partial class ExpedienteDetalladoDTO {
        
        private string organismoField;
        
        private string descripcionOrganismoField;
        
        private string preCuilField;
        
        private string docCuilField;
        
        private string digCuilField;
        
        private string tipoTramiteField;
        
        private string descripcionTipoTramiteField;
        
        private string secuenciaField;
        
        private string cExpeField;
        
        private string estadoField;
        
        private string descripcionEstadoField;
        
        private short tipoDocumentoField;
        
        private string descripcionTipoDocumentoField;
        
        private string numeroDocumentoField;
        
        private string docAdicionalDocumentoField;
        
        private string caratulaField;
        
        private string afjpField;
        
        private System.DateTime beneficioFacuField;
        
        private string beneficioExCajaField;
        
        private string beneficioTipoField;
        
        private string beneficioNumeroField;
        
        private string beneficioCoparticipeField;
        
        private string usuarioAltaField;
        
        private string ultimaOficinaField;
        
        private string descripcionUltimaOficinaField;
        
        private System.DateTime fechaVencimientoField;
        
        private string cInicField;
        
        private System.Nullable<System.DateTime> fechaInicioAFJPField;
        
        private System.DateTime fechaActualizacionField;
        
        private string codigoOficinaAltaField;
        
        private string descripcionOficinaAltaField;
        
        private System.Nullable<System.DateTime> fechaAltaField;
        
        private string nroRemitoPaseField;
        
        private string timeSalidaPaseField;
        
        private string usuarioSalidaPaseField;
        
        private string codOficinaSalidaField;
        
        private string descOficinaSalidaField;
        
        private System.Nullable<short> codSistemaSalidaField;
        
        private string descSistemaSalidaField;
        
        private string timeEntradaPaseField;
        
        private string usuarioEntradaPaseField;
        
        private string codOficinaEntradaField;
        
        private string descOficinaEntradaField;
        
        private System.Nullable<short> codSistemaEntradaField;
        
        private string descSistemaEntradaField;
        
        private string orgCabeceraField;
        
        private string cuilPreCabeceraField;
        
        private string cuilDocCabeceraField;
        
        private string cuilDigCabeceraField;
        
        private System.Nullable<int> tipoTramiteCabeceraField;
        
        private System.Nullable<int> secuenciaCabeceraField;
        
        private System.Nullable<long> codAgregacionField;
        
        private string descAgregacionField;
        
        private System.DateTime fiagCoDiField;
        
        private System.DateTime fvdiField;
        
        private System.DateTime fechaAltaRelacionField;
        
        private string timeActualizacionField;
        
        private System.Nullable<short> codSistemaCabeceraField;
        
        private string descSistemaCabeceraField;
        
        private string codEstadoHistField;
        
        private string descEstadoHistField;
        
        private string timeAltaHistField;
        
        private string codOficinaHistField;
        
        private string descOficinaHistField;
        
        private System.Nullable<short> codSistemaHistField;
        
        private string descSistemaHistField;
        
        private string usuarioHistField;
        
        private System.Nullable<decimal> cuilApoderadoField;
        
        private MatriculaAbogadoDTO matriculaField;
        
        private string timeAltaApoderadoField;
        
        private string usuarioAltaApoderadoField;
        
        private string cOficinaAltaApoderadoField;
        
        private string descOficinaAltaApoderadoField;
        
        private string cOrgActuMedicaField;
        
        private string preCuilActuMedicaField;
        
        private string docCuilActuMedicaField;
        
        private string digCuilActuMedicaField;
        
        private string cTipoActuMedicaField;
        
        private string cSeqActuMedicaField;
        
        private string cOficinaActuMedicaField;
        
        private string descOficinaActuMedicaField;
        
        private System.DateTime fechaUltGiroActuMedicaField;
        
        private string timeAltaActuMedicaField;
        
        private System.Nullable<short> codSistemaActuMedicaField;
        
        private string descSistemaActuMedicaField;
        
        private string estadoExpedienteResolucionField;
        
        private string descEstadoResolucionField;
        
        private string timeEstadoResolucionField;
        
        private System.Nullable<short> codSistemaResolucionField;
        
        private string descSistemaResolucionField;
        
        private System.Nullable<int> numeroResolucionField;
        
        private string codOficinaUsuarioResolucionField;
        
        private string codOperadorResolucionField;
        
        private string descripcionOperadorResolucionField;
        
        private System.DateTime fechaResolucionManualField;
        
        private string numeroResolucionManualField;
        
        private string timeActualizResolucionField;
        
        private string descOficinaUsuarioResolucionField;
        
        private System.Nullable<short> codProvinciaExpedienteProvincialField;
        
        private string descAbreviadaProvinciaExpedienteProvincialField;
        
        private string expedienteProvincialField;
        
        private string timeActualizaExpedienteProvincialField;
        
        private System.Nullable<short> codSistemaExpedienteProvincialField;
        
        private string descSistemaExpedienteProvincialField;
        
        /// <remarks/>
        public string organismo {
            get {
                return this.organismoField;
            }
            set {
                this.organismoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcionOrganismo {
            get {
                return this.descripcionOrganismoField;
            }
            set {
                this.descripcionOrganismoField = value;
            }
        }
        
        /// <remarks/>
        public string preCuil {
            get {
                return this.preCuilField;
            }
            set {
                this.preCuilField = value;
            }
        }
        
        /// <remarks/>
        public string docCuil {
            get {
                return this.docCuilField;
            }
            set {
                this.docCuilField = value;
            }
        }
        
        /// <remarks/>
        public string digCuil {
            get {
                return this.digCuilField;
            }
            set {
                this.digCuilField = value;
            }
        }
        
        /// <remarks/>
        public string tipoTramite {
            get {
                return this.tipoTramiteField;
            }
            set {
                this.tipoTramiteField = value;
            }
        }
        
        /// <remarks/>
        public string descripcionTipoTramite {
            get {
                return this.descripcionTipoTramiteField;
            }
            set {
                this.descripcionTipoTramiteField = value;
            }
        }
        
        /// <remarks/>
        public string secuencia {
            get {
                return this.secuenciaField;
            }
            set {
                this.secuenciaField = value;
            }
        }
        
        /// <remarks/>
        public string cExpe {
            get {
                return this.cExpeField;
            }
            set {
                this.cExpeField = value;
            }
        }
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcionEstado {
            get {
                return this.descripcionEstadoField;
            }
            set {
                this.descripcionEstadoField = value;
            }
        }
        
        /// <remarks/>
        public short tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcionTipoDocumento {
            get {
                return this.descripcionTipoDocumentoField;
            }
            set {
                this.descripcionTipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string docAdicionalDocumento {
            get {
                return this.docAdicionalDocumentoField;
            }
            set {
                this.docAdicionalDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string caratula {
            get {
                return this.caratulaField;
            }
            set {
                this.caratulaField = value;
            }
        }
        
        /// <remarks/>
        public string afjp {
            get {
                return this.afjpField;
            }
            set {
                this.afjpField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime beneficioFacu {
            get {
                return this.beneficioFacuField;
            }
            set {
                this.beneficioFacuField = value;
            }
        }
        
        /// <remarks/>
        public string beneficioExCaja {
            get {
                return this.beneficioExCajaField;
            }
            set {
                this.beneficioExCajaField = value;
            }
        }
        
        /// <remarks/>
        public string beneficioTipo {
            get {
                return this.beneficioTipoField;
            }
            set {
                this.beneficioTipoField = value;
            }
        }
        
        /// <remarks/>
        public string beneficioNumero {
            get {
                return this.beneficioNumeroField;
            }
            set {
                this.beneficioNumeroField = value;
            }
        }
        
        /// <remarks/>
        public string beneficioCoparticipe {
            get {
                return this.beneficioCoparticipeField;
            }
            set {
                this.beneficioCoparticipeField = value;
            }
        }
        
        /// <remarks/>
        public string usuarioAlta {
            get {
                return this.usuarioAltaField;
            }
            set {
                this.usuarioAltaField = value;
            }
        }
        
        /// <remarks/>
        public string ultimaOficina {
            get {
                return this.ultimaOficinaField;
            }
            set {
                this.ultimaOficinaField = value;
            }
        }
        
        /// <remarks/>
        public string descripcionUltimaOficina {
            get {
                return this.descripcionUltimaOficinaField;
            }
            set {
                this.descripcionUltimaOficinaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
            }
        }
        
        /// <remarks/>
        public string cInic {
            get {
                return this.cInicField;
            }
            set {
                this.cInicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechaInicioAFJP {
            get {
                return this.fechaInicioAFJPField;
            }
            set {
                this.fechaInicioAFJPField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaActualizacion {
            get {
                return this.fechaActualizacionField;
            }
            set {
                this.fechaActualizacionField = value;
            }
        }
        
        /// <remarks/>
        public string codigoOficinaAlta {
            get {
                return this.codigoOficinaAltaField;
            }
            set {
                this.codigoOficinaAltaField = value;
            }
        }
        
        /// <remarks/>
        public string descripcionOficinaAlta {
            get {
                return this.descripcionOficinaAltaField;
            }
            set {
                this.descripcionOficinaAltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechaAlta {
            get {
                return this.fechaAltaField;
            }
            set {
                this.fechaAltaField = value;
            }
        }
        
        /// <remarks/>
        public string nroRemitoPase {
            get {
                return this.nroRemitoPaseField;
            }
            set {
                this.nroRemitoPaseField = value;
            }
        }
        
        /// <remarks/>
        public string timeSalidaPase {
            get {
                return this.timeSalidaPaseField;
            }
            set {
                this.timeSalidaPaseField = value;
            }
        }
        
        /// <remarks/>
        public string usuarioSalidaPase {
            get {
                return this.usuarioSalidaPaseField;
            }
            set {
                this.usuarioSalidaPaseField = value;
            }
        }
        
        /// <remarks/>
        public string codOficinaSalida {
            get {
                return this.codOficinaSalidaField;
            }
            set {
                this.codOficinaSalidaField = value;
            }
        }
        
        /// <remarks/>
        public string descOficinaSalida {
            get {
                return this.descOficinaSalidaField;
            }
            set {
                this.descOficinaSalidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> codSistemaSalida {
            get {
                return this.codSistemaSalidaField;
            }
            set {
                this.codSistemaSalidaField = value;
            }
        }
        
        /// <remarks/>
        public string descSistemaSalida {
            get {
                return this.descSistemaSalidaField;
            }
            set {
                this.descSistemaSalidaField = value;
            }
        }
        
        /// <remarks/>
        public string timeEntradaPase {
            get {
                return this.timeEntradaPaseField;
            }
            set {
                this.timeEntradaPaseField = value;
            }
        }
        
        /// <remarks/>
        public string usuarioEntradaPase {
            get {
                return this.usuarioEntradaPaseField;
            }
            set {
                this.usuarioEntradaPaseField = value;
            }
        }
        
        /// <remarks/>
        public string codOficinaEntrada {
            get {
                return this.codOficinaEntradaField;
            }
            set {
                this.codOficinaEntradaField = value;
            }
        }
        
        /// <remarks/>
        public string descOficinaEntrada {
            get {
                return this.descOficinaEntradaField;
            }
            set {
                this.descOficinaEntradaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> codSistemaEntrada {
            get {
                return this.codSistemaEntradaField;
            }
            set {
                this.codSistemaEntradaField = value;
            }
        }
        
        /// <remarks/>
        public string descSistemaEntrada {
            get {
                return this.descSistemaEntradaField;
            }
            set {
                this.descSistemaEntradaField = value;
            }
        }
        
        /// <remarks/>
        public string orgCabecera {
            get {
                return this.orgCabeceraField;
            }
            set {
                this.orgCabeceraField = value;
            }
        }
        
        /// <remarks/>
        public string cuilPreCabecera {
            get {
                return this.cuilPreCabeceraField;
            }
            set {
                this.cuilPreCabeceraField = value;
            }
        }
        
        /// <remarks/>
        public string cuilDocCabecera {
            get {
                return this.cuilDocCabeceraField;
            }
            set {
                this.cuilDocCabeceraField = value;
            }
        }
        
        /// <remarks/>
        public string cuilDigCabecera {
            get {
                return this.cuilDigCabeceraField;
            }
            set {
                this.cuilDigCabeceraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tipoTramiteCabecera {
            get {
                return this.tipoTramiteCabeceraField;
            }
            set {
                this.tipoTramiteCabeceraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> secuenciaCabecera {
            get {
                return this.secuenciaCabeceraField;
            }
            set {
                this.secuenciaCabeceraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> codAgregacion {
            get {
                return this.codAgregacionField;
            }
            set {
                this.codAgregacionField = value;
            }
        }
        
        /// <remarks/>
        public string descAgregacion {
            get {
                return this.descAgregacionField;
            }
            set {
                this.descAgregacionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fiagCoDi {
            get {
                return this.fiagCoDiField;
            }
            set {
                this.fiagCoDiField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fvdi {
            get {
                return this.fvdiField;
            }
            set {
                this.fvdiField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaAltaRelacion {
            get {
                return this.fechaAltaRelacionField;
            }
            set {
                this.fechaAltaRelacionField = value;
            }
        }
        
        /// <remarks/>
        public string timeActualizacion {
            get {
                return this.timeActualizacionField;
            }
            set {
                this.timeActualizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> codSistemaCabecera {
            get {
                return this.codSistemaCabeceraField;
            }
            set {
                this.codSistemaCabeceraField = value;
            }
        }
        
        /// <remarks/>
        public string descSistemaCabecera {
            get {
                return this.descSistemaCabeceraField;
            }
            set {
                this.descSistemaCabeceraField = value;
            }
        }
        
        /// <remarks/>
        public string codEstadoHist {
            get {
                return this.codEstadoHistField;
            }
            set {
                this.codEstadoHistField = value;
            }
        }
        
        /// <remarks/>
        public string descEstadoHist {
            get {
                return this.descEstadoHistField;
            }
            set {
                this.descEstadoHistField = value;
            }
        }
        
        /// <remarks/>
        public string timeAltaHist {
            get {
                return this.timeAltaHistField;
            }
            set {
                this.timeAltaHistField = value;
            }
        }
        
        /// <remarks/>
        public string codOficinaHist {
            get {
                return this.codOficinaHistField;
            }
            set {
                this.codOficinaHistField = value;
            }
        }
        
        /// <remarks/>
        public string descOficinaHist {
            get {
                return this.descOficinaHistField;
            }
            set {
                this.descOficinaHistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> codSistemaHist {
            get {
                return this.codSistemaHistField;
            }
            set {
                this.codSistemaHistField = value;
            }
        }
        
        /// <remarks/>
        public string descSistemaHist {
            get {
                return this.descSistemaHistField;
            }
            set {
                this.descSistemaHistField = value;
            }
        }
        
        /// <remarks/>
        public string usuarioHist {
            get {
                return this.usuarioHistField;
            }
            set {
                this.usuarioHistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> cuilApoderado {
            get {
                return this.cuilApoderadoField;
            }
            set {
                this.cuilApoderadoField = value;
            }
        }
        
        /// <remarks/>
        public MatriculaAbogadoDTO matricula {
            get {
                return this.matriculaField;
            }
            set {
                this.matriculaField = value;
            }
        }
        
        /// <remarks/>
        public string timeAltaApoderado {
            get {
                return this.timeAltaApoderadoField;
            }
            set {
                this.timeAltaApoderadoField = value;
            }
        }
        
        /// <remarks/>
        public string usuarioAltaApoderado {
            get {
                return this.usuarioAltaApoderadoField;
            }
            set {
                this.usuarioAltaApoderadoField = value;
            }
        }
        
        /// <remarks/>
        public string cOficinaAltaApoderado {
            get {
                return this.cOficinaAltaApoderadoField;
            }
            set {
                this.cOficinaAltaApoderadoField = value;
            }
        }
        
        /// <remarks/>
        public string descOficinaAltaApoderado {
            get {
                return this.descOficinaAltaApoderadoField;
            }
            set {
                this.descOficinaAltaApoderadoField = value;
            }
        }
        
        /// <remarks/>
        public string cOrgActuMedica {
            get {
                return this.cOrgActuMedicaField;
            }
            set {
                this.cOrgActuMedicaField = value;
            }
        }
        
        /// <remarks/>
        public string preCuilActuMedica {
            get {
                return this.preCuilActuMedicaField;
            }
            set {
                this.preCuilActuMedicaField = value;
            }
        }
        
        /// <remarks/>
        public string docCuilActuMedica {
            get {
                return this.docCuilActuMedicaField;
            }
            set {
                this.docCuilActuMedicaField = value;
            }
        }
        
        /// <remarks/>
        public string digCuilActuMedica {
            get {
                return this.digCuilActuMedicaField;
            }
            set {
                this.digCuilActuMedicaField = value;
            }
        }
        
        /// <remarks/>
        public string cTipoActuMedica {
            get {
                return this.cTipoActuMedicaField;
            }
            set {
                this.cTipoActuMedicaField = value;
            }
        }
        
        /// <remarks/>
        public string cSeqActuMedica {
            get {
                return this.cSeqActuMedicaField;
            }
            set {
                this.cSeqActuMedicaField = value;
            }
        }
        
        /// <remarks/>
        public string cOficinaActuMedica {
            get {
                return this.cOficinaActuMedicaField;
            }
            set {
                this.cOficinaActuMedicaField = value;
            }
        }
        
        /// <remarks/>
        public string descOficinaActuMedica {
            get {
                return this.descOficinaActuMedicaField;
            }
            set {
                this.descOficinaActuMedicaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaUltGiroActuMedica {
            get {
                return this.fechaUltGiroActuMedicaField;
            }
            set {
                this.fechaUltGiroActuMedicaField = value;
            }
        }
        
        /// <remarks/>
        public string timeAltaActuMedica {
            get {
                return this.timeAltaActuMedicaField;
            }
            set {
                this.timeAltaActuMedicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> codSistemaActuMedica {
            get {
                return this.codSistemaActuMedicaField;
            }
            set {
                this.codSistemaActuMedicaField = value;
            }
        }
        
        /// <remarks/>
        public string descSistemaActuMedica {
            get {
                return this.descSistemaActuMedicaField;
            }
            set {
                this.descSistemaActuMedicaField = value;
            }
        }
        
        /// <remarks/>
        public string estadoExpedienteResolucion {
            get {
                return this.estadoExpedienteResolucionField;
            }
            set {
                this.estadoExpedienteResolucionField = value;
            }
        }
        
        /// <remarks/>
        public string descEstadoResolucion {
            get {
                return this.descEstadoResolucionField;
            }
            set {
                this.descEstadoResolucionField = value;
            }
        }
        
        /// <remarks/>
        public string timeEstadoResolucion {
            get {
                return this.timeEstadoResolucionField;
            }
            set {
                this.timeEstadoResolucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> codSistemaResolucion {
            get {
                return this.codSistemaResolucionField;
            }
            set {
                this.codSistemaResolucionField = value;
            }
        }
        
        /// <remarks/>
        public string descSistemaResolucion {
            get {
                return this.descSistemaResolucionField;
            }
            set {
                this.descSistemaResolucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> numeroResolucion {
            get {
                return this.numeroResolucionField;
            }
            set {
                this.numeroResolucionField = value;
            }
        }
        
        /// <remarks/>
        public string codOficinaUsuarioResolucion {
            get {
                return this.codOficinaUsuarioResolucionField;
            }
            set {
                this.codOficinaUsuarioResolucionField = value;
            }
        }
        
        /// <remarks/>
        public string codOperadorResolucion {
            get {
                return this.codOperadorResolucionField;
            }
            set {
                this.codOperadorResolucionField = value;
            }
        }
        
        /// <remarks/>
        public string descripcionOperadorResolucion {
            get {
                return this.descripcionOperadorResolucionField;
            }
            set {
                this.descripcionOperadorResolucionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaResolucionManual {
            get {
                return this.fechaResolucionManualField;
            }
            set {
                this.fechaResolucionManualField = value;
            }
        }
        
        /// <remarks/>
        public string numeroResolucionManual {
            get {
                return this.numeroResolucionManualField;
            }
            set {
                this.numeroResolucionManualField = value;
            }
        }
        
        /// <remarks/>
        public string timeActualizResolucion {
            get {
                return this.timeActualizResolucionField;
            }
            set {
                this.timeActualizResolucionField = value;
            }
        }
        
        /// <remarks/>
        public string descOficinaUsuarioResolucion {
            get {
                return this.descOficinaUsuarioResolucionField;
            }
            set {
                this.descOficinaUsuarioResolucionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> codProvinciaExpedienteProvincial {
            get {
                return this.codProvinciaExpedienteProvincialField;
            }
            set {
                this.codProvinciaExpedienteProvincialField = value;
            }
        }
        
        /// <remarks/>
        public string descAbreviadaProvinciaExpedienteProvincial {
            get {
                return this.descAbreviadaProvinciaExpedienteProvincialField;
            }
            set {
                this.descAbreviadaProvinciaExpedienteProvincialField = value;
            }
        }
        
        /// <remarks/>
        public string expedienteProvincial {
            get {
                return this.expedienteProvincialField;
            }
            set {
                this.expedienteProvincialField = value;
            }
        }
        
        /// <remarks/>
        public string timeActualizaExpedienteProvincial {
            get {
                return this.timeActualizaExpedienteProvincialField;
            }
            set {
                this.timeActualizaExpedienteProvincialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> codSistemaExpedienteProvincial {
            get {
                return this.codSistemaExpedienteProvincialField;
            }
            set {
                this.codSistemaExpedienteProvincialField = value;
            }
        }
        
        /// <remarks/>
        public string descSistemaExpedienteProvincial {
            get {
                return this.descSistemaExpedienteProvincialField;
            }
            set {
                this.descSistemaExpedienteProvincialField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anses.gov.ar/anme/")]
    public partial class ExpedienteIdDTO {
        
        private string organismoField;
        
        private string preCuilField;
        
        private string docCuilField;
        
        private string digCuilField;
        
        private string tipoTramiteField;
        
        private string secuenciaField;
        
        /// <remarks/>
        public string organismo {
            get {
                return this.organismoField;
            }
            set {
                this.organismoField = value;
            }
        }
        
        /// <remarks/>
        public string preCuil {
            get {
                return this.preCuilField;
            }
            set {
                this.preCuilField = value;
            }
        }
        
        /// <remarks/>
        public string docCuil {
            get {
                return this.docCuilField;
            }
            set {
                this.docCuilField = value;
            }
        }
        
        /// <remarks/>
        public string digCuil {
            get {
                return this.digCuilField;
            }
            set {
                this.digCuilField = value;
            }
        }
        
        /// <remarks/>
        public string tipoTramite {
            get {
                return this.tipoTramiteField;
            }
            set {
                this.tipoTramiteField = value;
            }
        }
        
        /// <remarks/>
        public string secuencia {
            get {
                return this.secuenciaField;
            }
            set {
                this.secuenciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anses.gov.ar/anme/")]
    public partial class TipoError {
        
        private short codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        public short codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://anses.gov.ar/anme/")]
    public partial class ExpedienteDTO {
        
        private string organismoField;
        
        private string preCuilField;
        
        private string docCuilField;
        
        private string digCuilField;
        
        private string tipoTramiteField;
        
        private string secuenciaField;
        
        private string codigoField;
        
        private string estadoField;
        
        private short tipoDocumentoField;
        
        private string numeroDocumentoField;
        
        private string docAdicionalDocumentoField;
        
        private string caratulaField;
        
        private System.DateTime beneficioFacuField;
        
        private string beneficioExCajaField;
        
        private string beneficioTipoField;
        
        private string beneficioNumeroField;
        
        private string beneficioCoparticipeField;
        
        private string usrAltaField;
        
        private string ultimaOficinaField;
        
        private System.DateTime fechaVencimientoField;
        
        private string estadoSentenciaField;
        
        private System.Nullable<System.DateTime> fechaAltaAFJPField;
        
        private System.DateTime fechaProcesoField;
        
        private string codigoOficinaAltaField;
        
        private System.Nullable<System.DateTime> fechaAltaField;
        
        /// <remarks/>
        public string organismo {
            get {
                return this.organismoField;
            }
            set {
                this.organismoField = value;
            }
        }
        
        /// <remarks/>
        public string preCuil {
            get {
                return this.preCuilField;
            }
            set {
                this.preCuilField = value;
            }
        }
        
        /// <remarks/>
        public string docCuil {
            get {
                return this.docCuilField;
            }
            set {
                this.docCuilField = value;
            }
        }
        
        /// <remarks/>
        public string digCuil {
            get {
                return this.digCuilField;
            }
            set {
                this.digCuilField = value;
            }
        }
        
        /// <remarks/>
        public string tipoTramite {
            get {
                return this.tipoTramiteField;
            }
            set {
                this.tipoTramiteField = value;
            }
        }
        
        /// <remarks/>
        public string secuencia {
            get {
                return this.secuenciaField;
            }
            set {
                this.secuenciaField = value;
            }
        }
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public short tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string docAdicionalDocumento {
            get {
                return this.docAdicionalDocumentoField;
            }
            set {
                this.docAdicionalDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string caratula {
            get {
                return this.caratulaField;
            }
            set {
                this.caratulaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime beneficioFacu {
            get {
                return this.beneficioFacuField;
            }
            set {
                this.beneficioFacuField = value;
            }
        }
        
        /// <remarks/>
        public string beneficioExCaja {
            get {
                return this.beneficioExCajaField;
            }
            set {
                this.beneficioExCajaField = value;
            }
        }
        
        /// <remarks/>
        public string beneficioTipo {
            get {
                return this.beneficioTipoField;
            }
            set {
                this.beneficioTipoField = value;
            }
        }
        
        /// <remarks/>
        public string beneficioNumero {
            get {
                return this.beneficioNumeroField;
            }
            set {
                this.beneficioNumeroField = value;
            }
        }
        
        /// <remarks/>
        public string beneficioCoparticipe {
            get {
                return this.beneficioCoparticipeField;
            }
            set {
                this.beneficioCoparticipeField = value;
            }
        }
        
        /// <remarks/>
        public string usrAlta {
            get {
                return this.usrAltaField;
            }
            set {
                this.usrAltaField = value;
            }
        }
        
        /// <remarks/>
        public string ultimaOficina {
            get {
                return this.ultimaOficinaField;
            }
            set {
                this.ultimaOficinaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaVencimiento {
            get {
                return this.fechaVencimientoField;
            }
            set {
                this.fechaVencimientoField = value;
            }
        }
        
        /// <remarks/>
        public string estadoSentencia {
            get {
                return this.estadoSentenciaField;
            }
            set {
                this.estadoSentenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechaAltaAFJP {
            get {
                return this.fechaAltaAFJPField;
            }
            set {
                this.fechaAltaAFJPField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaProceso {
            get {
                return this.fechaProcesoField;
            }
            set {
                this.fechaProcesoField = value;
            }
        }
        
        /// <remarks/>
        public string codigoOficinaAlta {
            get {
                return this.codigoOficinaAltaField;
            }
            set {
                this.codigoOficinaAltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechaAlta {
            get {
                return this.fechaAltaField;
            }
            set {
                this.fechaAltaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void BuscarExpedientesPorCuilCompletedEventHandler(object sender, BuscarExpedientesPorCuilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarExpedientesPorCuilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarExpedientesPorCuilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExpedienteDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExpedienteDTO[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TipoError error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoError)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void BuscarExpedientesPorCuilYTiposDeTramitesCompletedEventHandler(object sender, BuscarExpedientesPorCuilYTiposDeTramitesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarExpedientesPorCuilYTiposDeTramitesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarExpedientesPorCuilYTiposDeTramitesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExpedienteDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExpedienteDTO[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TipoError error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoError)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void BuscarExpedientesPorOrganismoYCuilYTiposDeTramitesCompletedEventHandler(object sender, BuscarExpedientesPorOrganismoYCuilYTiposDeTramitesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarExpedientesPorOrganismoYCuilYTiposDeTramitesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarExpedientesPorOrganismoYCuilYTiposDeTramitesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExpedienteDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExpedienteDTO[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TipoError error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoError)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void BuscarExpedientesPorTipoyNumeroDeDocumentoCompletedEventHandler(object sender, BuscarExpedientesPorTipoyNumeroDeDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarExpedientesPorTipoyNumeroDeDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarExpedientesPorTipoyNumeroDeDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExpedienteDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExpedienteDTO[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TipoError error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoError)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void BuscarExpedientesPorCuilYTipoyNumeroDeDocumentoCompletedEventHandler(object sender, BuscarExpedientesPorCuilYTipoyNumeroDeDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarExpedientesPorCuilYTipoyNumeroDeDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarExpedientesPorCuilYTipoyNumeroDeDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExpedienteDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExpedienteDTO[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TipoError error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoError)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void BuscarExpedienteDetalladoPorPKCompletedEventHandler(object sender, BuscarExpedienteDetalladoPorPKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarExpedienteDetalladoPorPKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarExpedienteDetalladoPorPKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExpedienteDetalladoDTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExpedienteDetalladoDTO)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TipoError error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoError)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void BuscarExpedientesPorBeneficioParaRHCompletedEventHandler(object sender, BuscarExpedientesPorBeneficioParaRHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarExpedientesPorBeneficioParaRHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarExpedientesPorBeneficioParaRHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExpedientePorBeneficioRHDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExpedientePorBeneficioRHDTO[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TipoError error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoError)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ConsultaExpedientesPorCuilListaGrupEstadisticoCompletedEventHandler(object sender, ConsultaExpedientesPorCuilListaGrupEstadisticoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaExpedientesPorCuilListaGrupEstadisticoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaExpedientesPorCuilListaGrupEstadisticoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExpedienteDTO[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExpedienteDTO[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TipoError error {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoError)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591