//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anses.ArgentaC.Negocio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ansesnegodesapp/uvLibretaWs/uvLibretaWS.asmx")]
        public string Anses_ArgentaC_Negocio_uvLibretaWS_uvLibretaWS {
            get {
                return ((string)(this["Anses_ArgentaC_Negocio_uvLibretaWS_uvLibretaWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ansesnegodesapp/Anses.Prissa.Carpeta.Invalidez.Servicio/CertificadosWS.asm" +
            "x")]
        public string Anses_ArgentaC_Negocio_CertificadosWS_CertificadosWS {
            get {
                return ((string)(this["Anses_ArgentaC_Negocio_CertificadosWS_CertificadosWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ansesnegodesapp/EmplBenefWS/EmplBenef.asmx")]
        public string Anses_ArgentaC_Negocio_EmplBenef_EmplBenef {
            get {
                return ((string)(this["Anses_ArgentaC_Negocio_EmplBenef_EmplBenef"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ansesnegodesapp/ANME/ANMEGestionTramites/ExpedienteWS.asmx")]
        public string Anses_ArgentaC_Negocio_ExpedienteWS_ExpedienteWS {
            get {
                return ((string)(this["Anses_ArgentaC_Negocio_ExpedienteWS_ExpedienteWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ansesnegodesapp/activos_ServiciosComplementariosWs/Activos_ServiciosComple" +
            "mentariosWs.asmx")]
        public string Anses_ArgentaC_Negocio_Activos_ServiciosComplementariosWs_Activos_ServiciosComplementariosWs {
            get {
                return ((string)(this["Anses_ArgentaC_Negocio_Activos_ServiciosComplementariosWs_Activos_ServiciosComple" +
                    "mentariosWs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ansesbiobancos1.anses.gov.ar/SBA/SBAService.svc")]
        public string Anses_ArgentaC_Negocio_SBAService_SBAService {
            get {
                return ((string)(this["Anses_ArgentaC_Negocio_SBAService_SBAService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ansesnegodesapp/BocaDePagoServicio/BocaDePagoWS.asmx")]
        public string Anses_ArgentaC_Negocio_BocaDePagoWS_BocaDePagoWS {
            get {
                return ((string)(this["Anses_ArgentaC_Negocio_BocaDePagoWS_BocaDePagoWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ansesnegodesapp/WebRUBWS/RUBConsultas01.asmx")]
        public string Anses_ArgentaC_Negocio_RUBConsultas01_RUBConsultas01 {
            get {
                return ((string)(this["Anses_ArgentaC_Negocio_RUBConsultas01_RUBConsultas01"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ansesnegodesapp/UVHICreditos/UVHICreditos.asmx")]
        public string Anses_ArgentaC_Negocio_UVHICreditos_UVHICreditos {
            get {
                return ((string)(this["Anses_ArgentaC_Negocio_UVHICreditos_UVHICreditos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ansesnegodesapp/NacionServicios_WCF/PIM.svc")]
        public string Anses_ArgentaC_Negocio_PIM_PIM {
            get {
                return ((string)(this["Anses_ArgentaC_Negocio_PIM_PIM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ansesnegodesapp/datserviciov2/NovedadWS.asmx")]
        public string Anses_ArgentaC_Negocio_NovedadAnsesWS_NovedadWS {
            get {
                return ((string)(this["Anses_ArgentaC_Negocio_NovedadAnsesWS_NovedadWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://presdesabper/ADPLocalizacionDB2SP/WSPW04.asmx")]
        public string Anses_ArgentaC_Negocio_WSPW04_WS_PW04 {
            get {
                return ((string)(this["Anses_ArgentaC_Negocio_WSPW04_WS_PW04"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://presdesabper/adplocalizaciondb2sp/datosdepersonaporcuip.asmx")]
        public string Anses_ArgentaC_Negocio_DatosdePersonaporCuip_DatosdePersonaporCuip {
            get {
                return ((string)(this["Anses_ArgentaC_Negocio_DatosdePersonaporCuip_DatosdePersonaporCuip"]));
            }
        }
    }
}
