//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Anses.ArgentaC.Negocio.UVHICreditos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UVHICreditosSoap", Namespace="http://yh.anses.gov.ar/")]
    public partial class UVHICreditos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DeudaTraerOperationCompleted;
        
        private System.Threading.SendOrPostCallback CuilInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CuilInfoSUAFOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidarDNIOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UVHICreditos() {
            this.Url = global::Anses.ArgentaC.Negocio.Properties.Settings.Default.Anses_ArgentaC_Negocio_UVHICreditos_UVHICreditos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DeudaTraerCompletedEventHandler DeudaTraerCompleted;
        
        /// <remarks/>
        public event CuilInfoCompletedEventHandler CuilInfoCompleted;
        
        /// <remarks/>
        public event CuilInfoSUAFCompletedEventHandler CuilInfoSUAFCompleted;
        
        /// <remarks/>
        public event ValidarDNICompletedEventHandler ValidarDNICompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://yh.anses.gov.ar/DeudaTraer", RequestNamespace="http://yh.anses.gov.ar/", ResponseNamespace="http://yh.anses.gov.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Deuda[] DeudaTraer(decimal pCuil) {
            object[] results = this.Invoke("DeudaTraer", new object[] {
                        pCuil});
            return ((Deuda[])(results[0]));
        }
        
        /// <remarks/>
        public void DeudaTraerAsync(decimal pCuil) {
            this.DeudaTraerAsync(pCuil, null);
        }
        
        /// <remarks/>
        public void DeudaTraerAsync(decimal pCuil, object userState) {
            if ((this.DeudaTraerOperationCompleted == null)) {
                this.DeudaTraerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeudaTraerOperationCompleted);
            }
            this.InvokeAsync("DeudaTraer", new object[] {
                        pCuil}, this.DeudaTraerOperationCompleted, userState);
        }
        
        private void OnDeudaTraerOperationCompleted(object arg) {
            if ((this.DeudaTraerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeudaTraerCompleted(this, new DeudaTraerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://yh.anses.gov.ar/CuilInfo", RequestNamespace="http://yh.anses.gov.ar/", ResponseNamespace="http://yh.anses.gov.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CCInfo[] CuilInfo(decimal pCuil) {
            object[] results = this.Invoke("CuilInfo", new object[] {
                        pCuil});
            return ((CCInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void CuilInfoAsync(decimal pCuil) {
            this.CuilInfoAsync(pCuil, null);
        }
        
        /// <remarks/>
        public void CuilInfoAsync(decimal pCuil, object userState) {
            if ((this.CuilInfoOperationCompleted == null)) {
                this.CuilInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCuilInfoOperationCompleted);
            }
            this.InvokeAsync("CuilInfo", new object[] {
                        pCuil}, this.CuilInfoOperationCompleted, userState);
        }
        
        private void OnCuilInfoOperationCompleted(object arg) {
            if ((this.CuilInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CuilInfoCompleted(this, new CuilInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://yh.anses.gov.ar/CuilInfoSUAF", RequestNamespace="http://yh.anses.gov.ar/", ResponseNamespace="http://yh.anses.gov.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CCInfo[] CuilInfoSUAF(decimal pCuil) {
            object[] results = this.Invoke("CuilInfoSUAF", new object[] {
                        pCuil});
            return ((CCInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void CuilInfoSUAFAsync(decimal pCuil) {
            this.CuilInfoSUAFAsync(pCuil, null);
        }
        
        /// <remarks/>
        public void CuilInfoSUAFAsync(decimal pCuil, object userState) {
            if ((this.CuilInfoSUAFOperationCompleted == null)) {
                this.CuilInfoSUAFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCuilInfoSUAFOperationCompleted);
            }
            this.InvokeAsync("CuilInfoSUAF", new object[] {
                        pCuil}, this.CuilInfoSUAFOperationCompleted, userState);
        }
        
        private void OnCuilInfoSUAFOperationCompleted(object arg) {
            if ((this.CuilInfoSUAFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CuilInfoSUAFCompleted(this, new CuilInfoSUAFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://yh.anses.gov.ar/ValidarDNI", RequestNamespace="http://yh.anses.gov.ar/", ResponseNamespace="http://yh.anses.gov.ar/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidarDNI(int Dni, string Sexo, int IdTramitedni) {
            object[] results = this.Invoke("ValidarDNI", new object[] {
                        Dni,
                        Sexo,
                        IdTramitedni});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarDNIAsync(int Dni, string Sexo, int IdTramitedni) {
            this.ValidarDNIAsync(Dni, Sexo, IdTramitedni, null);
        }
        
        /// <remarks/>
        public void ValidarDNIAsync(int Dni, string Sexo, int IdTramitedni, object userState) {
            if ((this.ValidarDNIOperationCompleted == null)) {
                this.ValidarDNIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarDNIOperationCompleted);
            }
            this.InvokeAsync("ValidarDNI", new object[] {
                        Dni,
                        Sexo,
                        IdTramitedni}, this.ValidarDNIOperationCompleted, userState);
        }
        
        private void OnValidarDNIOperationCompleted(object arg) {
            if ((this.ValidarDNICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarDNICompleted(this, new ValidarDNICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yh.anses.gov.ar/")]
    public partial class Deuda {
        
        private decimal nroBeneficioField;
        
        private int sistemaCodigoField;
        
        private string sistemaField;
        
        private decimal saldoField;
        
        /// <remarks/>
        public decimal NroBeneficio {
            get {
                return this.nroBeneficioField;
            }
            set {
                this.nroBeneficioField = value;
            }
        }
        
        /// <remarks/>
        public int SistemaCodigo {
            get {
                return this.sistemaCodigoField;
            }
            set {
                this.sistemaCodigoField = value;
            }
        }
        
        /// <remarks/>
        public string Sistema {
            get {
                return this.sistemaField;
            }
            set {
                this.sistemaField = value;
            }
        }
        
        /// <remarks/>
        public decimal Saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yh.anses.gov.ar/")]
    public partial class CCInfo {
        
        private decimal cuilField;
        
        private string apeNomField;
        
        private decimal cBU1Field;
        
        private decimal cBU2Field;
        
        private int bancoField;
        
        private int agenciaField;
        
        private decimal nroBeneficioField;
        
        private int docTipoField;
        
        private decimal docNumeroField;
        
        private string sexoField;
        
        private System.DateTime nacimientoField;
        
        private System.Nullable<System.DateTime> fallecimimentoField;
        
        private decimal valorBrutoField;
        
        private int prestacionField;
        
        private decimal rELCuilField;
        
        private string sEsDiscapacitadoField;
        
        private decimal afectacionDisponibleField;
        
        private decimal periodoAltaField;
        
        /// <remarks/>
        public decimal Cuil {
            get {
                return this.cuilField;
            }
            set {
                this.cuilField = value;
            }
        }
        
        /// <remarks/>
        public string ApeNom {
            get {
                return this.apeNomField;
            }
            set {
                this.apeNomField = value;
            }
        }
        
        /// <remarks/>
        public decimal CBU1 {
            get {
                return this.cBU1Field;
            }
            set {
                this.cBU1Field = value;
            }
        }
        
        /// <remarks/>
        public decimal CBU2 {
            get {
                return this.cBU2Field;
            }
            set {
                this.cBU2Field = value;
            }
        }
        
        /// <remarks/>
        public int Banco {
            get {
                return this.bancoField;
            }
            set {
                this.bancoField = value;
            }
        }
        
        /// <remarks/>
        public int Agencia {
            get {
                return this.agenciaField;
            }
            set {
                this.agenciaField = value;
            }
        }
        
        /// <remarks/>
        public decimal NroBeneficio {
            get {
                return this.nroBeneficioField;
            }
            set {
                this.nroBeneficioField = value;
            }
        }
        
        /// <remarks/>
        public int DocTipo {
            get {
                return this.docTipoField;
            }
            set {
                this.docTipoField = value;
            }
        }
        
        /// <remarks/>
        public decimal DocNumero {
            get {
                return this.docNumeroField;
            }
            set {
                this.docNumeroField = value;
            }
        }
        
        /// <remarks/>
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Nacimiento {
            get {
                return this.nacimientoField;
            }
            set {
                this.nacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Fallecimimento {
            get {
                return this.fallecimimentoField;
            }
            set {
                this.fallecimimentoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorBruto {
            get {
                return this.valorBrutoField;
            }
            set {
                this.valorBrutoField = value;
            }
        }
        
        /// <remarks/>
        public int Prestacion {
            get {
                return this.prestacionField;
            }
            set {
                this.prestacionField = value;
            }
        }
        
        /// <remarks/>
        public decimal RELCuil {
            get {
                return this.rELCuilField;
            }
            set {
                this.rELCuilField = value;
            }
        }
        
        /// <remarks/>
        public string sEsDiscapacitado {
            get {
                return this.sEsDiscapacitadoField;
            }
            set {
                this.sEsDiscapacitadoField = value;
            }
        }
        
        /// <remarks/>
        public decimal AfectacionDisponible {
            get {
                return this.afectacionDisponibleField;
            }
            set {
                this.afectacionDisponibleField = value;
            }
        }
        
        /// <remarks/>
        public decimal PeriodoAlta {
            get {
                return this.periodoAltaField;
            }
            set {
                this.periodoAltaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void DeudaTraerCompletedEventHandler(object sender, DeudaTraerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeudaTraerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeudaTraerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Deuda[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Deuda[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void CuilInfoCompletedEventHandler(object sender, CuilInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CuilInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CuilInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CCInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CCInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void CuilInfoSUAFCompletedEventHandler(object sender, CuilInfoSUAFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CuilInfoSUAFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CuilInfoSUAFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CCInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CCInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void ValidarDNICompletedEventHandler(object sender, ValidarDNICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarDNICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarDNICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591