//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Anses.ArgentaC.Negocio.SBAService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomBinding_ISBAService", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestDto))]
    public partial class SBAService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EnrollOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEnrollResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback IdentifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCuilStateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SBAService() {
            this.Url = global::Anses.ArgentaC.Negocio.Properties.Settings.Default.Anses_ArgentaC_Negocio_SBAService_SBAService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EnrollCompletedEventHandler EnrollCompleted;
        
        /// <remarks/>
        public event GetEnrollResultCompletedEventHandler GetEnrollResultCompleted;
        
        /// <remarks/>
        public event VerifyCompletedEventHandler VerifyCompleted;
        
        /// <remarks/>
        public event IdentifyCompletedEventHandler IdentifyCompleted;
        
        /// <remarks/>
        public event GetCuilStateCompletedEventHandler GetCuilStateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mihuella.anses.gov.ar/ISBAService/Enroll", RequestNamespace="http://mihuella.anses.gov.ar", ResponseNamespace="http://mihuella.anses.gov.ar", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EnrollResponseDto Enroll([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] EnrollRequestDto request) {
            object[] results = this.Invoke("Enroll", new object[] {
                        request});
            return ((EnrollResponseDto)(results[0]));
        }
        
        /// <remarks/>
        public void EnrollAsync(EnrollRequestDto request) {
            this.EnrollAsync(request, null);
        }
        
        /// <remarks/>
        public void EnrollAsync(EnrollRequestDto request, object userState) {
            if ((this.EnrollOperationCompleted == null)) {
                this.EnrollOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnrollOperationCompleted);
            }
            this.InvokeAsync("Enroll", new object[] {
                        request}, this.EnrollOperationCompleted, userState);
        }
        
        private void OnEnrollOperationCompleted(object arg) {
            if ((this.EnrollCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnrollCompleted(this, new EnrollCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mihuella.anses.gov.ar/ISBAService/GetEnrollResult", RequestNamespace="http://mihuella.anses.gov.ar", ResponseNamespace="http://mihuella.anses.gov.ar", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EnrollResultResponseDto GetEnrollResult([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] EnrollResultRequestDto request) {
            object[] results = this.Invoke("GetEnrollResult", new object[] {
                        request});
            return ((EnrollResultResponseDto)(results[0]));
        }
        
        /// <remarks/>
        public void GetEnrollResultAsync(EnrollResultRequestDto request) {
            this.GetEnrollResultAsync(request, null);
        }
        
        /// <remarks/>
        public void GetEnrollResultAsync(EnrollResultRequestDto request, object userState) {
            if ((this.GetEnrollResultOperationCompleted == null)) {
                this.GetEnrollResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEnrollResultOperationCompleted);
            }
            this.InvokeAsync("GetEnrollResult", new object[] {
                        request}, this.GetEnrollResultOperationCompleted, userState);
        }
        
        private void OnGetEnrollResultOperationCompleted(object arg) {
            if ((this.GetEnrollResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEnrollResultCompleted(this, new GetEnrollResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mihuella.anses.gov.ar/ISBAService/Verify", RequestNamespace="http://mihuella.anses.gov.ar", ResponseNamespace="http://mihuella.anses.gov.ar", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VerifyResponseDto Verify([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] VerifyRequestDto request) {
            object[] results = this.Invoke("Verify", new object[] {
                        request});
            return ((VerifyResponseDto)(results[0]));
        }
        
        /// <remarks/>
        public void VerifyAsync(VerifyRequestDto request) {
            this.VerifyAsync(request, null);
        }
        
        /// <remarks/>
        public void VerifyAsync(VerifyRequestDto request, object userState) {
            if ((this.VerifyOperationCompleted == null)) {
                this.VerifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerifyOperationCompleted);
            }
            this.InvokeAsync("Verify", new object[] {
                        request}, this.VerifyOperationCompleted, userState);
        }
        
        private void OnVerifyOperationCompleted(object arg) {
            if ((this.VerifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerifyCompleted(this, new VerifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mihuella.anses.gov.ar/ISBAService/Identify", RequestNamespace="http://mihuella.anses.gov.ar", ResponseNamespace="http://mihuella.anses.gov.ar", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public IdentifyResponseDto Identify([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] IdentifyRequestDto request) {
            object[] results = this.Invoke("Identify", new object[] {
                        request});
            return ((IdentifyResponseDto)(results[0]));
        }
        
        /// <remarks/>
        public void IdentifyAsync(IdentifyRequestDto request) {
            this.IdentifyAsync(request, null);
        }
        
        /// <remarks/>
        public void IdentifyAsync(IdentifyRequestDto request, object userState) {
            if ((this.IdentifyOperationCompleted == null)) {
                this.IdentifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIdentifyOperationCompleted);
            }
            this.InvokeAsync("Identify", new object[] {
                        request}, this.IdentifyOperationCompleted, userState);
        }
        
        private void OnIdentifyOperationCompleted(object arg) {
            if ((this.IdentifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IdentifyCompleted(this, new IdentifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mihuella.anses.gov.ar/ISBAService/GetCuilState", RequestNamespace="http://mihuella.anses.gov.ar", ResponseNamespace="http://mihuella.anses.gov.ar", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CuilStateResponseDto GetCuilState([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CuilStateRequestDto request) {
            object[] results = this.Invoke("GetCuilState", new object[] {
                        request});
            return ((CuilStateResponseDto)(results[0]));
        }
        
        /// <remarks/>
        public void GetCuilStateAsync(CuilStateRequestDto request) {
            this.GetCuilStateAsync(request, null);
        }
        
        /// <remarks/>
        public void GetCuilStateAsync(CuilStateRequestDto request, object userState) {
            if ((this.GetCuilStateOperationCompleted == null)) {
                this.GetCuilStateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCuilStateOperationCompleted);
            }
            this.InvokeAsync("GetCuilState", new object[] {
                        request}, this.GetCuilStateOperationCompleted, userState);
        }
        
        private void OnGetCuilStateOperationCompleted(object arg) {
            if ((this.GetCuilStateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCuilStateCompleted(this, new GetCuilStateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.DTO")]
    public partial class EnrollRequestDto : RequestDto {
        
        private DocumentDto documentField;
        
        private FingerDto[] fingersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DocumentDto Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public FingerDto[] Fingers {
            get {
                return this.fingersField;
            }
            set {
                this.fingersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.DTO")]
    public partial class DocumentDto {
        
        private string documentNumField;
        
        private string nationalityField;
        
        private string typeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DocumentNum {
            get {
                return this.documentNumField;
            }
            set {
                this.documentNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nationality {
            get {
                return this.nationalityField;
            }
            set {
                this.nationalityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TypeId {
            get {
                return this.typeIdField;
            }
            set {
                this.typeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.DTO")]
    public partial class ResponseMessageDto {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CuilStateResponseDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentifyResponseDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VerifyResponseDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnrollResultResponseDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnrollResponseDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.DTO")]
    public partial class ResponseDto {
        
        private ResponseMessageDto[] errorsField;
        
        private bool hasErrorsField;
        
        private bool hasErrorsFieldSpecified;
        
        private MetadataDto[] metadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ResponseMessageDto[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public bool HasErrors {
            get {
                return this.hasErrorsField;
            }
            set {
                this.hasErrorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasErrorsSpecified {
            get {
                return this.hasErrorsFieldSpecified;
            }
            set {
                this.hasErrorsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public MetadataDto[] Metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.DTO")]
    public partial class MetadataDto {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.DTO")]
    public partial class CuilStateResponseDto : ResponseDto {
        
        private ResponseMessageDto cuilStateField;
        
        private System.DateTime lastActivityDateField;
        
        private bool lastActivityDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseMessageDto CuilState {
            get {
                return this.cuilStateField;
            }
            set {
                this.cuilStateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastActivityDate {
            get {
                return this.lastActivityDateField;
            }
            set {
                this.lastActivityDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastActivityDateSpecified {
            get {
                return this.lastActivityDateFieldSpecified;
            }
            set {
                this.lastActivityDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.DTO")]
    public partial class IdentifyResponseDto : ResponseDto {
        
        private DocumentDto documentField;
        
        private ResponseMessageDto identifyStateField;
        
        private int transactionIdField;
        
        private bool transactionIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DocumentDto Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseMessageDto IdentifyState {
            get {
                return this.identifyStateField;
            }
            set {
                this.identifyStateField = value;
            }
        }
        
        /// <remarks/>
        public int TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionIdSpecified {
            get {
                return this.transactionIdFieldSpecified;
            }
            set {
                this.transactionIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.DTO")]
    public partial class VerifyResponseDto : ResponseDto {
        
        private int transactionIdField;
        
        private bool transactionIdFieldSpecified;
        
        private ResponseMessageDto verifyStateField;
        
        /// <remarks/>
        public int TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionIdSpecified {
            get {
                return this.transactionIdFieldSpecified;
            }
            set {
                this.transactionIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseMessageDto VerifyState {
            get {
                return this.verifyStateField;
            }
            set {
                this.verifyStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.DTO")]
    public partial class EnrollResultResponseDto : ResponseDto {
        
        private DocumentDto documentField;
        
        private ResponseMessageDto enrollStateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DocumentDto Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseMessageDto EnrollState {
            get {
                return this.enrollStateField;
            }
            set {
                this.enrollStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.DTO")]
    public partial class EnrollResponseDto : ResponseDto {
        
        private int transactionIdField;
        
        private bool transactionIdFieldSpecified;
        
        /// <remarks/>
        public int TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionIdSpecified {
            get {
                return this.transactionIdFieldSpecified;
            }
            set {
                this.transactionIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.DTO")]
    public partial class FingerDto {
        
        private FingerType fingerTypeField;
        
        private bool fingerTypeFieldSpecified;
        
        private FingerprintType fingerprintTypeField;
        
        private bool fingerprintTypeFieldSpecified;
        
        private bool isAmputationField;
        
        private bool isAmputationFieldSpecified;
        
        private byte[] templateField;
        
        private TemplateFormat templateFormatField;
        
        private bool templateFormatFieldSpecified;
        
        private byte[] wSQField;
        
        /// <remarks/>
        public FingerType FingerType {
            get {
                return this.fingerTypeField;
            }
            set {
                this.fingerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FingerTypeSpecified {
            get {
                return this.fingerTypeFieldSpecified;
            }
            set {
                this.fingerTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public FingerprintType FingerprintType {
            get {
                return this.fingerprintTypeField;
            }
            set {
                this.fingerprintTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FingerprintTypeSpecified {
            get {
                return this.fingerprintTypeFieldSpecified;
            }
            set {
                this.fingerprintTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsAmputation {
            get {
                return this.isAmputationField;
            }
            set {
                this.isAmputationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsAmputationSpecified {
            get {
                return this.isAmputationFieldSpecified;
            }
            set {
                this.isAmputationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] Template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
            }
        }
        
        /// <remarks/>
        public TemplateFormat TemplateFormat {
            get {
                return this.templateFormatField;
            }
            set {
                this.templateFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TemplateFormatSpecified {
            get {
                return this.templateFormatFieldSpecified;
            }
            set {
                this.templateFormatFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] WSQ {
            get {
                return this.wSQField;
            }
            set {
                this.wSQField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.Enums")]
    public enum FingerType {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        RightThumb,
        
        /// <remarks/>
        RightIndex,
        
        /// <remarks/>
        RightMiddle,
        
        /// <remarks/>
        RightRing,
        
        /// <remarks/>
        RightLittle,
        
        /// <remarks/>
        LeftThumb,
        
        /// <remarks/>
        LeftIndex,
        
        /// <remarks/>
        LeftMiddle,
        
        /// <remarks/>
        LeftRing,
        
        /// <remarks/>
        LeftLittle,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.Enums")]
    public enum FingerprintType {
        
        /// <remarks/>
        LatentImpression,
        
        /// <remarks/>
        LatentLift,
        
        /// <remarks/>
        LatentPhoto,
        
        /// <remarks/>
        LatentTracing,
        
        /// <remarks/>
        LiveScanContactless,
        
        /// <remarks/>
        LiveScanPlain,
        
        /// <remarks/>
        LiveScanRolled,
        
        /// <remarks/>
        NonliveScanPlain,
        
        /// <remarks/>
        NonliveScanRolled,
        
        /// <remarks/>
        Swipe,
        
        /// <remarks/>
        None,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.Enums")]
    public enum TemplateFormat {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        ANSI378,
        
        /// <remarks/>
        Neurotechnology,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CuilStateRequestDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IdentifyRequestDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VerifyRequestDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnrollResultRequestDto))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnrollRequestDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.DTO")]
    public partial class RequestDto {
        
        private string entityField;
        
        private MetadataDto[] metadataField;
        
        private string terminalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public MetadataDto[] Metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.DTO")]
    public partial class CuilStateRequestDto : RequestDto {
        
        private DocumentDto documentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DocumentDto Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.DTO")]
    public partial class IdentifyRequestDto : RequestDto {
        
        private FingerDto[] fingersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public FingerDto[] Fingers {
            get {
                return this.fingersField;
            }
            set {
                this.fingersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.DTO")]
    public partial class VerifyRequestDto : RequestDto {
        
        private DocumentDto documentField;
        
        private FingerDto[] fingersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DocumentDto Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public FingerDto[] Fingers {
            get {
                return this.fingersField;
            }
            set {
                this.fingersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ANSeS.SBA.ServicesContracts.DTO")]
    public partial class EnrollResultRequestDto : RequestDto {
        
        private int transactionIdField;
        
        private bool transactionIdFieldSpecified;
        
        /// <remarks/>
        public int TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionIdSpecified {
            get {
                return this.transactionIdFieldSpecified;
            }
            set {
                this.transactionIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void EnrollCompletedEventHandler(object sender, EnrollCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnrollCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnrollCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EnrollResponseDto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EnrollResponseDto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetEnrollResultCompletedEventHandler(object sender, GetEnrollResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEnrollResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEnrollResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EnrollResultResponseDto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EnrollResultResponseDto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void VerifyCompletedEventHandler(object sender, VerifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VerifyResponseDto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VerifyResponseDto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void IdentifyCompletedEventHandler(object sender, IdentifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IdentifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IdentifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IdentifyResponseDto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IdentifyResponseDto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void GetCuilStateCompletedEventHandler(object sender, GetCuilStateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCuilStateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCuilStateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CuilStateResponseDto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CuilStateResponseDto)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591